/*
OCPI charging profiles module

Specification for OCPIs charging profiles handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the ActiveChargingProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActiveChargingProfile{}

// ActiveChargingProfile struct for ActiveChargingProfile
type ActiveChargingProfile struct {
	StartDateTime string `json:"start_date_time"`
	ChargingProfile ChargingProfile `json:"charging_profile"`
}

// NewActiveChargingProfile instantiates a new ActiveChargingProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActiveChargingProfile(startDateTime string, chargingProfile ChargingProfile) *ActiveChargingProfile {
	this := ActiveChargingProfile{}
	this.StartDateTime = startDateTime
	this.ChargingProfile = chargingProfile
	return &this
}

// NewActiveChargingProfileWithDefaults instantiates a new ActiveChargingProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActiveChargingProfileWithDefaults() *ActiveChargingProfile {
	this := ActiveChargingProfile{}
	return &this
}

// GetStartDateTime returns the StartDateTime field value
func (o *ActiveChargingProfile) GetStartDateTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartDateTime
}

// GetStartDateTimeOk returns a tuple with the StartDateTime field value
// and a boolean to check if the value has been set.
func (o *ActiveChargingProfile) GetStartDateTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartDateTime, true
}

// SetStartDateTime sets field value
func (o *ActiveChargingProfile) SetStartDateTime(v string) {
	o.StartDateTime = v
}

// GetChargingProfile returns the ChargingProfile field value
func (o *ActiveChargingProfile) GetChargingProfile() ChargingProfile {
	if o == nil {
		var ret ChargingProfile
		return ret
	}

	return o.ChargingProfile
}

// GetChargingProfileOk returns a tuple with the ChargingProfile field value
// and a boolean to check if the value has been set.
func (o *ActiveChargingProfile) GetChargingProfileOk() (*ChargingProfile, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChargingProfile, true
}

// SetChargingProfile sets field value
func (o *ActiveChargingProfile) SetChargingProfile(v ChargingProfile) {
	o.ChargingProfile = v
}

func (o ActiveChargingProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActiveChargingProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start_date_time"] = o.StartDateTime
	toSerialize["charging_profile"] = o.ChargingProfile
	return toSerialize, nil
}

type NullableActiveChargingProfile struct {
	value *ActiveChargingProfile
	isSet bool
}

func (v NullableActiveChargingProfile) Get() *ActiveChargingProfile {
	return v.value
}

func (v *NullableActiveChargingProfile) Set(val *ActiveChargingProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableActiveChargingProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableActiveChargingProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActiveChargingProfile(val *ActiveChargingProfile) *NullableActiveChargingProfile {
	return &NullableActiveChargingProfile{value: val, isSet: true}
}

func (v NullableActiveChargingProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActiveChargingProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


