/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrBodyCdrLocationCoordinates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrBodyCdrLocationCoordinates{}

// CdrBodyCdrLocationCoordinates struct for CdrBodyCdrLocationCoordinates
type CdrBodyCdrLocationCoordinates struct {
	Latitude string `json:"latitude"`
	Longitude string `json:"longitude"`
}

// NewCdrBodyCdrLocationCoordinates instantiates a new CdrBodyCdrLocationCoordinates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrBodyCdrLocationCoordinates(latitude string, longitude string) *CdrBodyCdrLocationCoordinates {
	this := CdrBodyCdrLocationCoordinates{}
	this.Latitude = latitude
	this.Longitude = longitude
	return &this
}

// NewCdrBodyCdrLocationCoordinatesWithDefaults instantiates a new CdrBodyCdrLocationCoordinates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrBodyCdrLocationCoordinatesWithDefaults() *CdrBodyCdrLocationCoordinates {
	this := CdrBodyCdrLocationCoordinates{}
	return &this
}

// GetLatitude returns the Latitude field value
func (o *CdrBodyCdrLocationCoordinates) GetLatitude() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *CdrBodyCdrLocationCoordinates) GetLatitudeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *CdrBodyCdrLocationCoordinates) SetLatitude(v string) {
	o.Latitude = v
}

// GetLongitude returns the Longitude field value
func (o *CdrBodyCdrLocationCoordinates) GetLongitude() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *CdrBodyCdrLocationCoordinates) GetLongitudeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *CdrBodyCdrLocationCoordinates) SetLongitude(v string) {
	o.Longitude = v
}

func (o CdrBodyCdrLocationCoordinates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrBodyCdrLocationCoordinates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["latitude"] = o.Latitude
	toSerialize["longitude"] = o.Longitude
	return toSerialize, nil
}

type NullableCdrBodyCdrLocationCoordinates struct {
	value *CdrBodyCdrLocationCoordinates
	isSet bool
}

func (v NullableCdrBodyCdrLocationCoordinates) Get() *CdrBodyCdrLocationCoordinates {
	return v.value
}

func (v *NullableCdrBodyCdrLocationCoordinates) Set(val *CdrBodyCdrLocationCoordinates) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrBodyCdrLocationCoordinates) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrBodyCdrLocationCoordinates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrBodyCdrLocationCoordinates(val *CdrBodyCdrLocationCoordinates) *NullableCdrBodyCdrLocationCoordinates {
	return &NullableCdrBodyCdrLocationCoordinates{value: val, isSet: true}
}

func (v NullableCdrBodyCdrLocationCoordinates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrBodyCdrLocationCoordinates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


