/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrSignedDataSignedValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrSignedDataSignedValues{}

// CdrSignedDataSignedValues struct for CdrSignedDataSignedValues
type CdrSignedDataSignedValues struct {
	Nature string `json:"nature"`
	PlainData string `json:"plain_data"`
	SignedData string `json:"signed_data"`
}

// NewCdrSignedDataSignedValues instantiates a new CdrSignedDataSignedValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrSignedDataSignedValues(nature string, plainData string, signedData string) *CdrSignedDataSignedValues {
	this := CdrSignedDataSignedValues{}
	this.Nature = nature
	this.PlainData = plainData
	this.SignedData = signedData
	return &this
}

// NewCdrSignedDataSignedValuesWithDefaults instantiates a new CdrSignedDataSignedValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrSignedDataSignedValuesWithDefaults() *CdrSignedDataSignedValues {
	this := CdrSignedDataSignedValues{}
	return &this
}

// GetNature returns the Nature field value
func (o *CdrSignedDataSignedValues) GetNature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nature
}

// GetNatureOk returns a tuple with the Nature field value
// and a boolean to check if the value has been set.
func (o *CdrSignedDataSignedValues) GetNatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nature, true
}

// SetNature sets field value
func (o *CdrSignedDataSignedValues) SetNature(v string) {
	o.Nature = v
}

// GetPlainData returns the PlainData field value
func (o *CdrSignedDataSignedValues) GetPlainData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlainData
}

// GetPlainDataOk returns a tuple with the PlainData field value
// and a boolean to check if the value has been set.
func (o *CdrSignedDataSignedValues) GetPlainDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlainData, true
}

// SetPlainData sets field value
func (o *CdrSignedDataSignedValues) SetPlainData(v string) {
	o.PlainData = v
}

// GetSignedData returns the SignedData field value
func (o *CdrSignedDataSignedValues) GetSignedData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignedData
}

// GetSignedDataOk returns a tuple with the SignedData field value
// and a boolean to check if the value has been set.
func (o *CdrSignedDataSignedValues) GetSignedDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignedData, true
}

// SetSignedData sets field value
func (o *CdrSignedDataSignedValues) SetSignedData(v string) {
	o.SignedData = v
}

func (o CdrSignedDataSignedValues) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrSignedDataSignedValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nature"] = o.Nature
	toSerialize["plain_data"] = o.PlainData
	toSerialize["signed_data"] = o.SignedData
	return toSerialize, nil
}

type NullableCdrSignedDataSignedValues struct {
	value *CdrSignedDataSignedValues
	isSet bool
}

func (v NullableCdrSignedDataSignedValues) Get() *CdrSignedDataSignedValues {
	return v.value
}

func (v *NullableCdrSignedDataSignedValues) Set(val *CdrSignedDataSignedValues) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrSignedDataSignedValues) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrSignedDataSignedValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrSignedDataSignedValues(val *CdrSignedDataSignedValues) *NullableCdrSignedDataSignedValues {
	return &NullableCdrSignedDataSignedValues{value: val, isSet: true}
}

func (v NullableCdrSignedDataSignedValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrSignedDataSignedValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


