/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the SessionChargingPeriodsDimensions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionChargingPeriodsDimensions{}

// SessionChargingPeriodsDimensions struct for SessionChargingPeriodsDimensions
type SessionChargingPeriodsDimensions struct {
	Type string `json:"type"`
	Volume float32 `json:"volume"`
}

// NewSessionChargingPeriodsDimensions instantiates a new SessionChargingPeriodsDimensions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionChargingPeriodsDimensions(type_ string, volume float32) *SessionChargingPeriodsDimensions {
	this := SessionChargingPeriodsDimensions{}
	this.Type = type_
	this.Volume = volume
	return &this
}

// NewSessionChargingPeriodsDimensionsWithDefaults instantiates a new SessionChargingPeriodsDimensions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionChargingPeriodsDimensionsWithDefaults() *SessionChargingPeriodsDimensions {
	this := SessionChargingPeriodsDimensions{}
	return &this
}

// GetType returns the Type field value
func (o *SessionChargingPeriodsDimensions) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SessionChargingPeriodsDimensions) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SessionChargingPeriodsDimensions) SetType(v string) {
	o.Type = v
}

// GetVolume returns the Volume field value
func (o *SessionChargingPeriodsDimensions) GetVolume() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value
// and a boolean to check if the value has been set.
func (o *SessionChargingPeriodsDimensions) GetVolumeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Volume, true
}

// SetVolume sets field value
func (o *SessionChargingPeriodsDimensions) SetVolume(v float32) {
	o.Volume = v
}

func (o SessionChargingPeriodsDimensions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionChargingPeriodsDimensions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["volume"] = o.Volume
	return toSerialize, nil
}

type NullableSessionChargingPeriodsDimensions struct {
	value *SessionChargingPeriodsDimensions
	isSet bool
}

func (v NullableSessionChargingPeriodsDimensions) Get() *SessionChargingPeriodsDimensions {
	return v.value
}

func (v *NullableSessionChargingPeriodsDimensions) Set(val *SessionChargingPeriodsDimensions) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionChargingPeriodsDimensions) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionChargingPeriodsDimensions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionChargingPeriodsDimensions(val *SessionChargingPeriodsDimensions) *NullableSessionChargingPeriodsDimensions {
	return &NullableSessionChargingPeriodsDimensions{value: val, isSet: true}
}

func (v NullableSessionChargingPeriodsDimensions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionChargingPeriodsDimensions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


