/*
OCPI hub client info module

Specification for OCPIs hub client info handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the ClientInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientInfoResponse{}

// ClientInfoResponse struct for ClientInfoResponse
type ClientInfoResponse struct {
	ClientsInfo *ClientInfo `json:"clients_info,omitempty"`
	StatusCode float32 `json:"status_code"`
	StatusMessage *string `json:"status_message,omitempty"`
	TimeStamp *string `json:"timeStamp,omitempty"`
}

// NewClientInfoResponse instantiates a new ClientInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientInfoResponse(statusCode float32) *ClientInfoResponse {
	this := ClientInfoResponse{}
	this.StatusCode = statusCode
	return &this
}

// NewClientInfoResponseWithDefaults instantiates a new ClientInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientInfoResponseWithDefaults() *ClientInfoResponse {
	this := ClientInfoResponse{}
	return &this
}

// GetClientsInfo returns the ClientsInfo field value if set, zero value otherwise.
func (o *ClientInfoResponse) GetClientsInfo() ClientInfo {
	if o == nil || IsNil(o.ClientsInfo) {
		var ret ClientInfo
		return ret
	}
	return *o.ClientsInfo
}

// GetClientsInfoOk returns a tuple with the ClientsInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientInfoResponse) GetClientsInfoOk() (*ClientInfo, bool) {
	if o == nil || IsNil(o.ClientsInfo) {
		return nil, false
	}
	return o.ClientsInfo, true
}

// HasClientsInfo returns a boolean if a field has been set.
func (o *ClientInfoResponse) HasClientsInfo() bool {
	if o != nil && !IsNil(o.ClientsInfo) {
		return true
	}

	return false
}

// SetClientsInfo gets a reference to the given ClientInfo and assigns it to the ClientsInfo field.
func (o *ClientInfoResponse) SetClientsInfo(v ClientInfo) {
	o.ClientsInfo = &v
}

// GetStatusCode returns the StatusCode field value
func (o *ClientInfoResponse) GetStatusCode() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *ClientInfoResponse) GetStatusCodeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *ClientInfoResponse) SetStatusCode(v float32) {
	o.StatusCode = v
}

// GetStatusMessage returns the StatusMessage field value if set, zero value otherwise.
func (o *ClientInfoResponse) GetStatusMessage() string {
	if o == nil || IsNil(o.StatusMessage) {
		var ret string
		return ret
	}
	return *o.StatusMessage
}

// GetStatusMessageOk returns a tuple with the StatusMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientInfoResponse) GetStatusMessageOk() (*string, bool) {
	if o == nil || IsNil(o.StatusMessage) {
		return nil, false
	}
	return o.StatusMessage, true
}

// HasStatusMessage returns a boolean if a field has been set.
func (o *ClientInfoResponse) HasStatusMessage() bool {
	if o != nil && !IsNil(o.StatusMessage) {
		return true
	}

	return false
}

// SetStatusMessage gets a reference to the given string and assigns it to the StatusMessage field.
func (o *ClientInfoResponse) SetStatusMessage(v string) {
	o.StatusMessage = &v
}

// GetTimeStamp returns the TimeStamp field value if set, zero value otherwise.
func (o *ClientInfoResponse) GetTimeStamp() string {
	if o == nil || IsNil(o.TimeStamp) {
		var ret string
		return ret
	}
	return *o.TimeStamp
}

// GetTimeStampOk returns a tuple with the TimeStamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientInfoResponse) GetTimeStampOk() (*string, bool) {
	if o == nil || IsNil(o.TimeStamp) {
		return nil, false
	}
	return o.TimeStamp, true
}

// HasTimeStamp returns a boolean if a field has been set.
func (o *ClientInfoResponse) HasTimeStamp() bool {
	if o != nil && !IsNil(o.TimeStamp) {
		return true
	}

	return false
}

// SetTimeStamp gets a reference to the given string and assigns it to the TimeStamp field.
func (o *ClientInfoResponse) SetTimeStamp(v string) {
	o.TimeStamp = &v
}

func (o ClientInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientsInfo) {
		toSerialize["clients_info"] = o.ClientsInfo
	}
	toSerialize["status_code"] = o.StatusCode
	if !IsNil(o.StatusMessage) {
		toSerialize["status_message"] = o.StatusMessage
	}
	if !IsNil(o.TimeStamp) {
		toSerialize["timeStamp"] = o.TimeStamp
	}
	return toSerialize, nil
}

type NullableClientInfoResponse struct {
	value *ClientInfoResponse
	isSet bool
}

func (v NullableClientInfoResponse) Get() *ClientInfoResponse {
	return v.value
}

func (v *NullableClientInfoResponse) Set(val *ClientInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientInfoResponse(val *ClientInfoResponse) *NullableClientInfoResponse {
	return &NullableClientInfoResponse{value: val, isSet: true}
}

func (v NullableClientInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


