/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrBodyTariffsEnergyMix type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrBodyTariffsEnergyMix{}

// CdrBodyTariffsEnergyMix struct for CdrBodyTariffsEnergyMix
type CdrBodyTariffsEnergyMix struct {
	IsGreenEnergy bool `json:"is_green_energy"`
	EnergySources *CdrBodyTariffsEnergyMixEnergySources `json:"energy_sources,omitempty"`
	EnvironImpact *CdrBodyTariffsEnergyMixEnvironImpact `json:"environ_impact,omitempty"`
	SupplierName *string `json:"supplier_name,omitempty"`
	EnergyProductName *string `json:"energy_product_name,omitempty"`
}

// NewCdrBodyTariffsEnergyMix instantiates a new CdrBodyTariffsEnergyMix object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrBodyTariffsEnergyMix(isGreenEnergy bool) *CdrBodyTariffsEnergyMix {
	this := CdrBodyTariffsEnergyMix{}
	this.IsGreenEnergy = isGreenEnergy
	return &this
}

// NewCdrBodyTariffsEnergyMixWithDefaults instantiates a new CdrBodyTariffsEnergyMix object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrBodyTariffsEnergyMixWithDefaults() *CdrBodyTariffsEnergyMix {
	this := CdrBodyTariffsEnergyMix{}
	return &this
}

// GetIsGreenEnergy returns the IsGreenEnergy field value
func (o *CdrBodyTariffsEnergyMix) GetIsGreenEnergy() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsGreenEnergy
}

// GetIsGreenEnergyOk returns a tuple with the IsGreenEnergy field value
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsEnergyMix) GetIsGreenEnergyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsGreenEnergy, true
}

// SetIsGreenEnergy sets field value
func (o *CdrBodyTariffsEnergyMix) SetIsGreenEnergy(v bool) {
	o.IsGreenEnergy = v
}

// GetEnergySources returns the EnergySources field value if set, zero value otherwise.
func (o *CdrBodyTariffsEnergyMix) GetEnergySources() CdrBodyTariffsEnergyMixEnergySources {
	if o == nil || IsNil(o.EnergySources) {
		var ret CdrBodyTariffsEnergyMixEnergySources
		return ret
	}
	return *o.EnergySources
}

// GetEnergySourcesOk returns a tuple with the EnergySources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsEnergyMix) GetEnergySourcesOk() (*CdrBodyTariffsEnergyMixEnergySources, bool) {
	if o == nil || IsNil(o.EnergySources) {
		return nil, false
	}
	return o.EnergySources, true
}

// HasEnergySources returns a boolean if a field has been set.
func (o *CdrBodyTariffsEnergyMix) HasEnergySources() bool {
	if o != nil && !IsNil(o.EnergySources) {
		return true
	}

	return false
}

// SetEnergySources gets a reference to the given CdrBodyTariffsEnergyMixEnergySources and assigns it to the EnergySources field.
func (o *CdrBodyTariffsEnergyMix) SetEnergySources(v CdrBodyTariffsEnergyMixEnergySources) {
	o.EnergySources = &v
}

// GetEnvironImpact returns the EnvironImpact field value if set, zero value otherwise.
func (o *CdrBodyTariffsEnergyMix) GetEnvironImpact() CdrBodyTariffsEnergyMixEnvironImpact {
	if o == nil || IsNil(o.EnvironImpact) {
		var ret CdrBodyTariffsEnergyMixEnvironImpact
		return ret
	}
	return *o.EnvironImpact
}

// GetEnvironImpactOk returns a tuple with the EnvironImpact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsEnergyMix) GetEnvironImpactOk() (*CdrBodyTariffsEnergyMixEnvironImpact, bool) {
	if o == nil || IsNil(o.EnvironImpact) {
		return nil, false
	}
	return o.EnvironImpact, true
}

// HasEnvironImpact returns a boolean if a field has been set.
func (o *CdrBodyTariffsEnergyMix) HasEnvironImpact() bool {
	if o != nil && !IsNil(o.EnvironImpact) {
		return true
	}

	return false
}

// SetEnvironImpact gets a reference to the given CdrBodyTariffsEnergyMixEnvironImpact and assigns it to the EnvironImpact field.
func (o *CdrBodyTariffsEnergyMix) SetEnvironImpact(v CdrBodyTariffsEnergyMixEnvironImpact) {
	o.EnvironImpact = &v
}

// GetSupplierName returns the SupplierName field value if set, zero value otherwise.
func (o *CdrBodyTariffsEnergyMix) GetSupplierName() string {
	if o == nil || IsNil(o.SupplierName) {
		var ret string
		return ret
	}
	return *o.SupplierName
}

// GetSupplierNameOk returns a tuple with the SupplierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsEnergyMix) GetSupplierNameOk() (*string, bool) {
	if o == nil || IsNil(o.SupplierName) {
		return nil, false
	}
	return o.SupplierName, true
}

// HasSupplierName returns a boolean if a field has been set.
func (o *CdrBodyTariffsEnergyMix) HasSupplierName() bool {
	if o != nil && !IsNil(o.SupplierName) {
		return true
	}

	return false
}

// SetSupplierName gets a reference to the given string and assigns it to the SupplierName field.
func (o *CdrBodyTariffsEnergyMix) SetSupplierName(v string) {
	o.SupplierName = &v
}

// GetEnergyProductName returns the EnergyProductName field value if set, zero value otherwise.
func (o *CdrBodyTariffsEnergyMix) GetEnergyProductName() string {
	if o == nil || IsNil(o.EnergyProductName) {
		var ret string
		return ret
	}
	return *o.EnergyProductName
}

// GetEnergyProductNameOk returns a tuple with the EnergyProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsEnergyMix) GetEnergyProductNameOk() (*string, bool) {
	if o == nil || IsNil(o.EnergyProductName) {
		return nil, false
	}
	return o.EnergyProductName, true
}

// HasEnergyProductName returns a boolean if a field has been set.
func (o *CdrBodyTariffsEnergyMix) HasEnergyProductName() bool {
	if o != nil && !IsNil(o.EnergyProductName) {
		return true
	}

	return false
}

// SetEnergyProductName gets a reference to the given string and assigns it to the EnergyProductName field.
func (o *CdrBodyTariffsEnergyMix) SetEnergyProductName(v string) {
	o.EnergyProductName = &v
}

func (o CdrBodyTariffsEnergyMix) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrBodyTariffsEnergyMix) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["is_green_energy"] = o.IsGreenEnergy
	if !IsNil(o.EnergySources) {
		toSerialize["energy_sources"] = o.EnergySources
	}
	if !IsNil(o.EnvironImpact) {
		toSerialize["environ_impact"] = o.EnvironImpact
	}
	if !IsNil(o.SupplierName) {
		toSerialize["supplier_name"] = o.SupplierName
	}
	if !IsNil(o.EnergyProductName) {
		toSerialize["energy_product_name"] = o.EnergyProductName
	}
	return toSerialize, nil
}

type NullableCdrBodyTariffsEnergyMix struct {
	value *CdrBodyTariffsEnergyMix
	isSet bool
}

func (v NullableCdrBodyTariffsEnergyMix) Get() *CdrBodyTariffsEnergyMix {
	return v.value
}

func (v *NullableCdrBodyTariffsEnergyMix) Set(val *CdrBodyTariffsEnergyMix) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrBodyTariffsEnergyMix) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrBodyTariffsEnergyMix) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrBodyTariffsEnergyMix(val *CdrBodyTariffsEnergyMix) *NullableCdrBodyTariffsEnergyMix {
	return &NullableCdrBodyTariffsEnergyMix{value: val, isSet: true}
}

func (v NullableCdrBodyTariffsEnergyMix) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrBodyTariffsEnergyMix) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


