/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrBodyTariffsTariffAltText type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrBodyTariffsTariffAltText{}

// CdrBodyTariffsTariffAltText struct for CdrBodyTariffsTariffAltText
type CdrBodyTariffsTariffAltText struct {
	Language string `json:"language"`
	Text string `json:"text"`
}

// NewCdrBodyTariffsTariffAltText instantiates a new CdrBodyTariffsTariffAltText object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrBodyTariffsTariffAltText(language string, text string) *CdrBodyTariffsTariffAltText {
	this := CdrBodyTariffsTariffAltText{}
	this.Language = language
	this.Text = text
	return &this
}

// NewCdrBodyTariffsTariffAltTextWithDefaults instantiates a new CdrBodyTariffsTariffAltText object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrBodyTariffsTariffAltTextWithDefaults() *CdrBodyTariffsTariffAltText {
	this := CdrBodyTariffsTariffAltText{}
	return &this
}

// GetLanguage returns the Language field value
func (o *CdrBodyTariffsTariffAltText) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsTariffAltText) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *CdrBodyTariffsTariffAltText) SetLanguage(v string) {
	o.Language = v
}

// GetText returns the Text field value
func (o *CdrBodyTariffsTariffAltText) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsTariffAltText) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *CdrBodyTariffsTariffAltText) SetText(v string) {
	o.Text = v
}

func (o CdrBodyTariffsTariffAltText) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrBodyTariffsTariffAltText) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["language"] = o.Language
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

type NullableCdrBodyTariffsTariffAltText struct {
	value *CdrBodyTariffsTariffAltText
	isSet bool
}

func (v NullableCdrBodyTariffsTariffAltText) Get() *CdrBodyTariffsTariffAltText {
	return v.value
}

func (v *NullableCdrBodyTariffsTariffAltText) Set(val *CdrBodyTariffsTariffAltText) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrBodyTariffsTariffAltText) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrBodyTariffsTariffAltText) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrBodyTariffsTariffAltText(val *CdrBodyTariffsTariffAltText) *NullableCdrBodyTariffsTariffAltText {
	return &NullableCdrBodyTariffsTariffAltText{value: val, isSet: true}
}

func (v NullableCdrBodyTariffsTariffAltText) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrBodyTariffsTariffAltText) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


