/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrChargingPeriodsDimensions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrChargingPeriodsDimensions{}

// CdrChargingPeriodsDimensions struct for CdrChargingPeriodsDimensions
type CdrChargingPeriodsDimensions struct {
	Type string `json:"type"`
	Volume float32 `json:"volume"`
}

// NewCdrChargingPeriodsDimensions instantiates a new CdrChargingPeriodsDimensions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrChargingPeriodsDimensions(type_ string, volume float32) *CdrChargingPeriodsDimensions {
	this := CdrChargingPeriodsDimensions{}
	this.Type = type_
	this.Volume = volume
	return &this
}

// NewCdrChargingPeriodsDimensionsWithDefaults instantiates a new CdrChargingPeriodsDimensions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrChargingPeriodsDimensionsWithDefaults() *CdrChargingPeriodsDimensions {
	this := CdrChargingPeriodsDimensions{}
	return &this
}

// GetType returns the Type field value
func (o *CdrChargingPeriodsDimensions) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CdrChargingPeriodsDimensions) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CdrChargingPeriodsDimensions) SetType(v string) {
	o.Type = v
}

// GetVolume returns the Volume field value
func (o *CdrChargingPeriodsDimensions) GetVolume() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value
// and a boolean to check if the value has been set.
func (o *CdrChargingPeriodsDimensions) GetVolumeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Volume, true
}

// SetVolume sets field value
func (o *CdrChargingPeriodsDimensions) SetVolume(v float32) {
	o.Volume = v
}

func (o CdrChargingPeriodsDimensions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrChargingPeriodsDimensions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["volume"] = o.Volume
	return toSerialize, nil
}

type NullableCdrChargingPeriodsDimensions struct {
	value *CdrChargingPeriodsDimensions
	isSet bool
}

func (v NullableCdrChargingPeriodsDimensions) Get() *CdrChargingPeriodsDimensions {
	return v.value
}

func (v *NullableCdrChargingPeriodsDimensions) Set(val *CdrChargingPeriodsDimensions) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrChargingPeriodsDimensions) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrChargingPeriodsDimensions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrChargingPeriodsDimensions(val *CdrChargingPeriodsDimensions) *NullableCdrChargingPeriodsDimensions {
	return &NullableCdrChargingPeriodsDimensions{value: val, isSet: true}
}

func (v NullableCdrChargingPeriodsDimensions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrChargingPeriodsDimensions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


