/*
OCPI locations module

Specification for OCPIs locations handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the LocationsDataEnergyMix type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocationsDataEnergyMix{}

// LocationsDataEnergyMix struct for LocationsDataEnergyMix
type LocationsDataEnergyMix struct {
	IsGreenEnergy bool `json:"is_green_energy"`
	EnergySources *LocationsDataEnergyMixEnergySources `json:"energy_sources,omitempty"`
	EnvironImpact *LocationsDataEnergyMixEnvironImpact `json:"environ_impact,omitempty"`
	SupplierName *string `json:"supplier_name,omitempty"`
	EnergyProductName *string `json:"energy_product_name,omitempty"`
}

// NewLocationsDataEnergyMix instantiates a new LocationsDataEnergyMix object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocationsDataEnergyMix(isGreenEnergy bool) *LocationsDataEnergyMix {
	this := LocationsDataEnergyMix{}
	this.IsGreenEnergy = isGreenEnergy
	return &this
}

// NewLocationsDataEnergyMixWithDefaults instantiates a new LocationsDataEnergyMix object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationsDataEnergyMixWithDefaults() *LocationsDataEnergyMix {
	this := LocationsDataEnergyMix{}
	return &this
}

// GetIsGreenEnergy returns the IsGreenEnergy field value
func (o *LocationsDataEnergyMix) GetIsGreenEnergy() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsGreenEnergy
}

// GetIsGreenEnergyOk returns a tuple with the IsGreenEnergy field value
// and a boolean to check if the value has been set.
func (o *LocationsDataEnergyMix) GetIsGreenEnergyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsGreenEnergy, true
}

// SetIsGreenEnergy sets field value
func (o *LocationsDataEnergyMix) SetIsGreenEnergy(v bool) {
	o.IsGreenEnergy = v
}

// GetEnergySources returns the EnergySources field value if set, zero value otherwise.
func (o *LocationsDataEnergyMix) GetEnergySources() LocationsDataEnergyMixEnergySources {
	if o == nil || IsNil(o.EnergySources) {
		var ret LocationsDataEnergyMixEnergySources
		return ret
	}
	return *o.EnergySources
}

// GetEnergySourcesOk returns a tuple with the EnergySources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationsDataEnergyMix) GetEnergySourcesOk() (*LocationsDataEnergyMixEnergySources, bool) {
	if o == nil || IsNil(o.EnergySources) {
		return nil, false
	}
	return o.EnergySources, true
}

// HasEnergySources returns a boolean if a field has been set.
func (o *LocationsDataEnergyMix) HasEnergySources() bool {
	if o != nil && !IsNil(o.EnergySources) {
		return true
	}

	return false
}

// SetEnergySources gets a reference to the given LocationsDataEnergyMixEnergySources and assigns it to the EnergySources field.
func (o *LocationsDataEnergyMix) SetEnergySources(v LocationsDataEnergyMixEnergySources) {
	o.EnergySources = &v
}

// GetEnvironImpact returns the EnvironImpact field value if set, zero value otherwise.
func (o *LocationsDataEnergyMix) GetEnvironImpact() LocationsDataEnergyMixEnvironImpact {
	if o == nil || IsNil(o.EnvironImpact) {
		var ret LocationsDataEnergyMixEnvironImpact
		return ret
	}
	return *o.EnvironImpact
}

// GetEnvironImpactOk returns a tuple with the EnvironImpact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationsDataEnergyMix) GetEnvironImpactOk() (*LocationsDataEnergyMixEnvironImpact, bool) {
	if o == nil || IsNil(o.EnvironImpact) {
		return nil, false
	}
	return o.EnvironImpact, true
}

// HasEnvironImpact returns a boolean if a field has been set.
func (o *LocationsDataEnergyMix) HasEnvironImpact() bool {
	if o != nil && !IsNil(o.EnvironImpact) {
		return true
	}

	return false
}

// SetEnvironImpact gets a reference to the given LocationsDataEnergyMixEnvironImpact and assigns it to the EnvironImpact field.
func (o *LocationsDataEnergyMix) SetEnvironImpact(v LocationsDataEnergyMixEnvironImpact) {
	o.EnvironImpact = &v
}

// GetSupplierName returns the SupplierName field value if set, zero value otherwise.
func (o *LocationsDataEnergyMix) GetSupplierName() string {
	if o == nil || IsNil(o.SupplierName) {
		var ret string
		return ret
	}
	return *o.SupplierName
}

// GetSupplierNameOk returns a tuple with the SupplierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationsDataEnergyMix) GetSupplierNameOk() (*string, bool) {
	if o == nil || IsNil(o.SupplierName) {
		return nil, false
	}
	return o.SupplierName, true
}

// HasSupplierName returns a boolean if a field has been set.
func (o *LocationsDataEnergyMix) HasSupplierName() bool {
	if o != nil && !IsNil(o.SupplierName) {
		return true
	}

	return false
}

// SetSupplierName gets a reference to the given string and assigns it to the SupplierName field.
func (o *LocationsDataEnergyMix) SetSupplierName(v string) {
	o.SupplierName = &v
}

// GetEnergyProductName returns the EnergyProductName field value if set, zero value otherwise.
func (o *LocationsDataEnergyMix) GetEnergyProductName() string {
	if o == nil || IsNil(o.EnergyProductName) {
		var ret string
		return ret
	}
	return *o.EnergyProductName
}

// GetEnergyProductNameOk returns a tuple with the EnergyProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationsDataEnergyMix) GetEnergyProductNameOk() (*string, bool) {
	if o == nil || IsNil(o.EnergyProductName) {
		return nil, false
	}
	return o.EnergyProductName, true
}

// HasEnergyProductName returns a boolean if a field has been set.
func (o *LocationsDataEnergyMix) HasEnergyProductName() bool {
	if o != nil && !IsNil(o.EnergyProductName) {
		return true
	}

	return false
}

// SetEnergyProductName gets a reference to the given string and assigns it to the EnergyProductName field.
func (o *LocationsDataEnergyMix) SetEnergyProductName(v string) {
	o.EnergyProductName = &v
}

func (o LocationsDataEnergyMix) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocationsDataEnergyMix) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["is_green_energy"] = o.IsGreenEnergy
	if !IsNil(o.EnergySources) {
		toSerialize["energy_sources"] = o.EnergySources
	}
	if !IsNil(o.EnvironImpact) {
		toSerialize["environ_impact"] = o.EnvironImpact
	}
	if !IsNil(o.SupplierName) {
		toSerialize["supplier_name"] = o.SupplierName
	}
	if !IsNil(o.EnergyProductName) {
		toSerialize["energy_product_name"] = o.EnergyProductName
	}
	return toSerialize, nil
}

type NullableLocationsDataEnergyMix struct {
	value *LocationsDataEnergyMix
	isSet bool
}

func (v NullableLocationsDataEnergyMix) Get() *LocationsDataEnergyMix {
	return v.value
}

func (v *NullableLocationsDataEnergyMix) Set(val *LocationsDataEnergyMix) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationsDataEnergyMix) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationsDataEnergyMix) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationsDataEnergyMix(val *LocationsDataEnergyMix) *NullableLocationsDataEnergyMix {
	return &NullableLocationsDataEnergyMix{value: val, isSet: true}
}

func (v NullableLocationsDataEnergyMix) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationsDataEnergyMix) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


