/*
OCPI commands module

Specification for OCPIs commands handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the UnlockConnector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnlockConnector{}

// UnlockConnector struct for UnlockConnector
type UnlockConnector struct {
	ResponseUrl string `json:"response_url"`
	LocationId string `json:"location_id"`
	EvseUid string `json:"evse_uid"`
	ConnectorId string `json:"connector_id"`
}

// NewUnlockConnector instantiates a new UnlockConnector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnlockConnector(responseUrl string, locationId string, evseUid string, connectorId string) *UnlockConnector {
	this := UnlockConnector{}
	this.ResponseUrl = responseUrl
	this.LocationId = locationId
	this.EvseUid = evseUid
	this.ConnectorId = connectorId
	return &this
}

// NewUnlockConnectorWithDefaults instantiates a new UnlockConnector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnlockConnectorWithDefaults() *UnlockConnector {
	this := UnlockConnector{}
	return &this
}

// GetResponseUrl returns the ResponseUrl field value
func (o *UnlockConnector) GetResponseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResponseUrl
}

// GetResponseUrlOk returns a tuple with the ResponseUrl field value
// and a boolean to check if the value has been set.
func (o *UnlockConnector) GetResponseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseUrl, true
}

// SetResponseUrl sets field value
func (o *UnlockConnector) SetResponseUrl(v string) {
	o.ResponseUrl = v
}

// GetLocationId returns the LocationId field value
func (o *UnlockConnector) GetLocationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value
// and a boolean to check if the value has been set.
func (o *UnlockConnector) GetLocationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationId, true
}

// SetLocationId sets field value
func (o *UnlockConnector) SetLocationId(v string) {
	o.LocationId = v
}

// GetEvseUid returns the EvseUid field value
func (o *UnlockConnector) GetEvseUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EvseUid
}

// GetEvseUidOk returns a tuple with the EvseUid field value
// and a boolean to check if the value has been set.
func (o *UnlockConnector) GetEvseUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EvseUid, true
}

// SetEvseUid sets field value
func (o *UnlockConnector) SetEvseUid(v string) {
	o.EvseUid = v
}

// GetConnectorId returns the ConnectorId field value
func (o *UnlockConnector) GetConnectorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectorId
}

// GetConnectorIdOk returns a tuple with the ConnectorId field value
// and a boolean to check if the value has been set.
func (o *UnlockConnector) GetConnectorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectorId, true
}

// SetConnectorId sets field value
func (o *UnlockConnector) SetConnectorId(v string) {
	o.ConnectorId = v
}

func (o UnlockConnector) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnlockConnector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["response_url"] = o.ResponseUrl
	toSerialize["location_id"] = o.LocationId
	toSerialize["evse_uid"] = o.EvseUid
	toSerialize["connector_id"] = o.ConnectorId
	return toSerialize, nil
}

type NullableUnlockConnector struct {
	value *UnlockConnector
	isSet bool
}

func (v NullableUnlockConnector) Get() *UnlockConnector {
	return v.value
}

func (v *NullableUnlockConnector) Set(val *UnlockConnector) {
	v.value = val
	v.isSet = true
}

func (v NullableUnlockConnector) IsSet() bool {
	return v.isSet
}

func (v *NullableUnlockConnector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnlockConnector(val *UnlockConnector) *NullableUnlockConnector {
	return &NullableUnlockConnector{value: val, isSet: true}
}

func (v NullableUnlockConnector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnlockConnector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


