/*
OCPI locations module

Specification for OCPIs locations handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the LocationsDataCoordinates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocationsDataCoordinates{}

// LocationsDataCoordinates struct for LocationsDataCoordinates
type LocationsDataCoordinates struct {
	Latitude string `json:"latitude"`
	Longitude string `json:"longitude"`
}

// NewLocationsDataCoordinates instantiates a new LocationsDataCoordinates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocationsDataCoordinates(latitude string, longitude string) *LocationsDataCoordinates {
	this := LocationsDataCoordinates{}
	this.Latitude = latitude
	this.Longitude = longitude
	return &this
}

// NewLocationsDataCoordinatesWithDefaults instantiates a new LocationsDataCoordinates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationsDataCoordinatesWithDefaults() *LocationsDataCoordinates {
	this := LocationsDataCoordinates{}
	return &this
}

// GetLatitude returns the Latitude field value
func (o *LocationsDataCoordinates) GetLatitude() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *LocationsDataCoordinates) GetLatitudeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *LocationsDataCoordinates) SetLatitude(v string) {
	o.Latitude = v
}

// GetLongitude returns the Longitude field value
func (o *LocationsDataCoordinates) GetLongitude() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *LocationsDataCoordinates) GetLongitudeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *LocationsDataCoordinates) SetLongitude(v string) {
	o.Longitude = v
}

func (o LocationsDataCoordinates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocationsDataCoordinates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["latitude"] = o.Latitude
	toSerialize["longitude"] = o.Longitude
	return toSerialize, nil
}

type NullableLocationsDataCoordinates struct {
	value *LocationsDataCoordinates
	isSet bool
}

func (v NullableLocationsDataCoordinates) Get() *LocationsDataCoordinates {
	return v.value
}

func (v *NullableLocationsDataCoordinates) Set(val *LocationsDataCoordinates) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationsDataCoordinates) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationsDataCoordinates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationsDataCoordinates(val *LocationsDataCoordinates) *NullableLocationsDataCoordinates {
	return &NullableLocationsDataCoordinates{value: val, isSet: true}
}

func (v NullableLocationsDataCoordinates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationsDataCoordinates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


