/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrTariffs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrTariffs{}

// CdrTariffs struct for CdrTariffs
type CdrTariffs struct {
	CountryCode string `json:"country_code"`
	PartyId string `json:"party_id"`
	Id string `json:"id"`
	Currency string `json:"currency"`
	Type *string `json:"type,omitempty"`
	TariffAltText *CdrTariffsTariffAltText `json:"tariff_alt_text,omitempty"`
	TariffAltUrl *string `json:"tariff_alt_url,omitempty"`
	MinPrice *Price `json:"min_price,omitempty"`
	MaxPrice *Price `json:"max_price,omitempty"`
	Elements *CdrTariffsElements `json:"elements,omitempty"`
	StartDateTime *string `json:"start_date_time,omitempty"`
	EndDateTime *string `json:"end_date_time,omitempty"`
	EnergyMix *CdrTariffsEnergyMix `json:"energy_mix,omitempty"`
	LastUpdated string `json:"last_updated"`
}

// NewCdrTariffs instantiates a new CdrTariffs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrTariffs(countryCode string, partyId string, id string, currency string, lastUpdated string) *CdrTariffs {
	this := CdrTariffs{}
	this.CountryCode = countryCode
	this.PartyId = partyId
	this.Id = id
	this.Currency = currency
	this.LastUpdated = lastUpdated
	return &this
}

// NewCdrTariffsWithDefaults instantiates a new CdrTariffs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrTariffsWithDefaults() *CdrTariffs {
	this := CdrTariffs{}
	return &this
}

// GetCountryCode returns the CountryCode field value
func (o *CdrTariffs) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *CdrTariffs) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetPartyId returns the PartyId field value
func (o *CdrTariffs) GetPartyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartyId
}

// GetPartyIdOk returns a tuple with the PartyId field value
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetPartyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartyId, true
}

// SetPartyId sets field value
func (o *CdrTariffs) SetPartyId(v string) {
	o.PartyId = v
}

// GetId returns the Id field value
func (o *CdrTariffs) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CdrTariffs) SetId(v string) {
	o.Id = v
}

// GetCurrency returns the Currency field value
func (o *CdrTariffs) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *CdrTariffs) SetCurrency(v string) {
	o.Currency = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CdrTariffs) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CdrTariffs) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CdrTariffs) SetType(v string) {
	o.Type = &v
}

// GetTariffAltText returns the TariffAltText field value if set, zero value otherwise.
func (o *CdrTariffs) GetTariffAltText() CdrTariffsTariffAltText {
	if o == nil || IsNil(o.TariffAltText) {
		var ret CdrTariffsTariffAltText
		return ret
	}
	return *o.TariffAltText
}

// GetTariffAltTextOk returns a tuple with the TariffAltText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetTariffAltTextOk() (*CdrTariffsTariffAltText, bool) {
	if o == nil || IsNil(o.TariffAltText) {
		return nil, false
	}
	return o.TariffAltText, true
}

// HasTariffAltText returns a boolean if a field has been set.
func (o *CdrTariffs) HasTariffAltText() bool {
	if o != nil && !IsNil(o.TariffAltText) {
		return true
	}

	return false
}

// SetTariffAltText gets a reference to the given CdrTariffsTariffAltText and assigns it to the TariffAltText field.
func (o *CdrTariffs) SetTariffAltText(v CdrTariffsTariffAltText) {
	o.TariffAltText = &v
}

// GetTariffAltUrl returns the TariffAltUrl field value if set, zero value otherwise.
func (o *CdrTariffs) GetTariffAltUrl() string {
	if o == nil || IsNil(o.TariffAltUrl) {
		var ret string
		return ret
	}
	return *o.TariffAltUrl
}

// GetTariffAltUrlOk returns a tuple with the TariffAltUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetTariffAltUrlOk() (*string, bool) {
	if o == nil || IsNil(o.TariffAltUrl) {
		return nil, false
	}
	return o.TariffAltUrl, true
}

// HasTariffAltUrl returns a boolean if a field has been set.
func (o *CdrTariffs) HasTariffAltUrl() bool {
	if o != nil && !IsNil(o.TariffAltUrl) {
		return true
	}

	return false
}

// SetTariffAltUrl gets a reference to the given string and assigns it to the TariffAltUrl field.
func (o *CdrTariffs) SetTariffAltUrl(v string) {
	o.TariffAltUrl = &v
}

// GetMinPrice returns the MinPrice field value if set, zero value otherwise.
func (o *CdrTariffs) GetMinPrice() Price {
	if o == nil || IsNil(o.MinPrice) {
		var ret Price
		return ret
	}
	return *o.MinPrice
}

// GetMinPriceOk returns a tuple with the MinPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetMinPriceOk() (*Price, bool) {
	if o == nil || IsNil(o.MinPrice) {
		return nil, false
	}
	return o.MinPrice, true
}

// HasMinPrice returns a boolean if a field has been set.
func (o *CdrTariffs) HasMinPrice() bool {
	if o != nil && !IsNil(o.MinPrice) {
		return true
	}

	return false
}

// SetMinPrice gets a reference to the given Price and assigns it to the MinPrice field.
func (o *CdrTariffs) SetMinPrice(v Price) {
	o.MinPrice = &v
}

// GetMaxPrice returns the MaxPrice field value if set, zero value otherwise.
func (o *CdrTariffs) GetMaxPrice() Price {
	if o == nil || IsNil(o.MaxPrice) {
		var ret Price
		return ret
	}
	return *o.MaxPrice
}

// GetMaxPriceOk returns a tuple with the MaxPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetMaxPriceOk() (*Price, bool) {
	if o == nil || IsNil(o.MaxPrice) {
		return nil, false
	}
	return o.MaxPrice, true
}

// HasMaxPrice returns a boolean if a field has been set.
func (o *CdrTariffs) HasMaxPrice() bool {
	if o != nil && !IsNil(o.MaxPrice) {
		return true
	}

	return false
}

// SetMaxPrice gets a reference to the given Price and assigns it to the MaxPrice field.
func (o *CdrTariffs) SetMaxPrice(v Price) {
	o.MaxPrice = &v
}

// GetElements returns the Elements field value if set, zero value otherwise.
func (o *CdrTariffs) GetElements() CdrTariffsElements {
	if o == nil || IsNil(o.Elements) {
		var ret CdrTariffsElements
		return ret
	}
	return *o.Elements
}

// GetElementsOk returns a tuple with the Elements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetElementsOk() (*CdrTariffsElements, bool) {
	if o == nil || IsNil(o.Elements) {
		return nil, false
	}
	return o.Elements, true
}

// HasElements returns a boolean if a field has been set.
func (o *CdrTariffs) HasElements() bool {
	if o != nil && !IsNil(o.Elements) {
		return true
	}

	return false
}

// SetElements gets a reference to the given CdrTariffsElements and assigns it to the Elements field.
func (o *CdrTariffs) SetElements(v CdrTariffsElements) {
	o.Elements = &v
}

// GetStartDateTime returns the StartDateTime field value if set, zero value otherwise.
func (o *CdrTariffs) GetStartDateTime() string {
	if o == nil || IsNil(o.StartDateTime) {
		var ret string
		return ret
	}
	return *o.StartDateTime
}

// GetStartDateTimeOk returns a tuple with the StartDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetStartDateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.StartDateTime) {
		return nil, false
	}
	return o.StartDateTime, true
}

// HasStartDateTime returns a boolean if a field has been set.
func (o *CdrTariffs) HasStartDateTime() bool {
	if o != nil && !IsNil(o.StartDateTime) {
		return true
	}

	return false
}

// SetStartDateTime gets a reference to the given string and assigns it to the StartDateTime field.
func (o *CdrTariffs) SetStartDateTime(v string) {
	o.StartDateTime = &v
}

// GetEndDateTime returns the EndDateTime field value if set, zero value otherwise.
func (o *CdrTariffs) GetEndDateTime() string {
	if o == nil || IsNil(o.EndDateTime) {
		var ret string
		return ret
	}
	return *o.EndDateTime
}

// GetEndDateTimeOk returns a tuple with the EndDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetEndDateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.EndDateTime) {
		return nil, false
	}
	return o.EndDateTime, true
}

// HasEndDateTime returns a boolean if a field has been set.
func (o *CdrTariffs) HasEndDateTime() bool {
	if o != nil && !IsNil(o.EndDateTime) {
		return true
	}

	return false
}

// SetEndDateTime gets a reference to the given string and assigns it to the EndDateTime field.
func (o *CdrTariffs) SetEndDateTime(v string) {
	o.EndDateTime = &v
}

// GetEnergyMix returns the EnergyMix field value if set, zero value otherwise.
func (o *CdrTariffs) GetEnergyMix() CdrTariffsEnergyMix {
	if o == nil || IsNil(o.EnergyMix) {
		var ret CdrTariffsEnergyMix
		return ret
	}
	return *o.EnergyMix
}

// GetEnergyMixOk returns a tuple with the EnergyMix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetEnergyMixOk() (*CdrTariffsEnergyMix, bool) {
	if o == nil || IsNil(o.EnergyMix) {
		return nil, false
	}
	return o.EnergyMix, true
}

// HasEnergyMix returns a boolean if a field has been set.
func (o *CdrTariffs) HasEnergyMix() bool {
	if o != nil && !IsNil(o.EnergyMix) {
		return true
	}

	return false
}

// SetEnergyMix gets a reference to the given CdrTariffsEnergyMix and assigns it to the EnergyMix field.
func (o *CdrTariffs) SetEnergyMix(v CdrTariffsEnergyMix) {
	o.EnergyMix = &v
}

// GetLastUpdated returns the LastUpdated field value
func (o *CdrTariffs) GetLastUpdated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
func (o *CdrTariffs) GetLastUpdatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdated, true
}

// SetLastUpdated sets field value
func (o *CdrTariffs) SetLastUpdated(v string) {
	o.LastUpdated = v
}

func (o CdrTariffs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrTariffs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["country_code"] = o.CountryCode
	toSerialize["party_id"] = o.PartyId
	toSerialize["id"] = o.Id
	toSerialize["currency"] = o.Currency
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.TariffAltText) {
		toSerialize["tariff_alt_text"] = o.TariffAltText
	}
	if !IsNil(o.TariffAltUrl) {
		toSerialize["tariff_alt_url"] = o.TariffAltUrl
	}
	if !IsNil(o.MinPrice) {
		toSerialize["min_price"] = o.MinPrice
	}
	if !IsNil(o.MaxPrice) {
		toSerialize["max_price"] = o.MaxPrice
	}
	if !IsNil(o.Elements) {
		toSerialize["elements"] = o.Elements
	}
	if !IsNil(o.StartDateTime) {
		toSerialize["start_date_time"] = o.StartDateTime
	}
	if !IsNil(o.EndDateTime) {
		toSerialize["end_date_time"] = o.EndDateTime
	}
	if !IsNil(o.EnergyMix) {
		toSerialize["energy_mix"] = o.EnergyMix
	}
	toSerialize["last_updated"] = o.LastUpdated
	return toSerialize, nil
}

type NullableCdrTariffs struct {
	value *CdrTariffs
	isSet bool
}

func (v NullableCdrTariffs) Get() *CdrTariffs {
	return v.value
}

func (v *NullableCdrTariffs) Set(val *CdrTariffs) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrTariffs) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrTariffs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrTariffs(val *CdrTariffs) *NullableCdrTariffs {
	return &NullableCdrTariffs{value: val, isSet: true}
}

func (v NullableCdrTariffs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrTariffs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


