/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrTariffsEnergyMixEnergySources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrTariffsEnergyMixEnergySources{}

// CdrTariffsEnergyMixEnergySources struct for CdrTariffsEnergyMixEnergySources
type CdrTariffsEnergyMixEnergySources struct {
	Source string `json:"source"`
	Percentage float32 `json:"percentage"`
}

// NewCdrTariffsEnergyMixEnergySources instantiates a new CdrTariffsEnergyMixEnergySources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrTariffsEnergyMixEnergySources(source string, percentage float32) *CdrTariffsEnergyMixEnergySources {
	this := CdrTariffsEnergyMixEnergySources{}
	this.Source = source
	this.Percentage = percentage
	return &this
}

// NewCdrTariffsEnergyMixEnergySourcesWithDefaults instantiates a new CdrTariffsEnergyMixEnergySources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrTariffsEnergyMixEnergySourcesWithDefaults() *CdrTariffsEnergyMixEnergySources {
	this := CdrTariffsEnergyMixEnergySources{}
	return &this
}

// GetSource returns the Source field value
func (o *CdrTariffsEnergyMixEnergySources) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *CdrTariffsEnergyMixEnergySources) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *CdrTariffsEnergyMixEnergySources) SetSource(v string) {
	o.Source = v
}

// GetPercentage returns the Percentage field value
func (o *CdrTariffsEnergyMixEnergySources) GetPercentage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value
// and a boolean to check if the value has been set.
func (o *CdrTariffsEnergyMixEnergySources) GetPercentageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percentage, true
}

// SetPercentage sets field value
func (o *CdrTariffsEnergyMixEnergySources) SetPercentage(v float32) {
	o.Percentage = v
}

func (o CdrTariffsEnergyMixEnergySources) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrTariffsEnergyMixEnergySources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["percentage"] = o.Percentage
	return toSerialize, nil
}

type NullableCdrTariffsEnergyMixEnergySources struct {
	value *CdrTariffsEnergyMixEnergySources
	isSet bool
}

func (v NullableCdrTariffsEnergyMixEnergySources) Get() *CdrTariffsEnergyMixEnergySources {
	return v.value
}

func (v *NullableCdrTariffsEnergyMixEnergySources) Set(val *CdrTariffsEnergyMixEnergySources) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrTariffsEnergyMixEnergySources) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrTariffsEnergyMixEnergySources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrTariffsEnergyMixEnergySources(val *CdrTariffsEnergyMixEnergySources) *NullableCdrTariffsEnergyMixEnergySources {
	return &NullableCdrTariffsEnergyMixEnergySources{value: val, isSet: true}
}

func (v NullableCdrTariffsEnergyMixEnergySources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrTariffsEnergyMixEnergySources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


