/*
OCPI charging profiles module

Specification for OCPIs charging profiles handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the SetChargingProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetChargingProfile{}

// SetChargingProfile struct for SetChargingProfile
type SetChargingProfile struct {
	ChargingProfile ChargingProfile `json:"charging_profile"`
	ResponseUrl string `json:"response_url"`
}

// NewSetChargingProfile instantiates a new SetChargingProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetChargingProfile(chargingProfile ChargingProfile, responseUrl string) *SetChargingProfile {
	this := SetChargingProfile{}
	this.ChargingProfile = chargingProfile
	this.ResponseUrl = responseUrl
	return &this
}

// NewSetChargingProfileWithDefaults instantiates a new SetChargingProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetChargingProfileWithDefaults() *SetChargingProfile {
	this := SetChargingProfile{}
	return &this
}

// GetChargingProfile returns the ChargingProfile field value
func (o *SetChargingProfile) GetChargingProfile() ChargingProfile {
	if o == nil {
		var ret ChargingProfile
		return ret
	}

	return o.ChargingProfile
}

// GetChargingProfileOk returns a tuple with the ChargingProfile field value
// and a boolean to check if the value has been set.
func (o *SetChargingProfile) GetChargingProfileOk() (*ChargingProfile, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChargingProfile, true
}

// SetChargingProfile sets field value
func (o *SetChargingProfile) SetChargingProfile(v ChargingProfile) {
	o.ChargingProfile = v
}

// GetResponseUrl returns the ResponseUrl field value
func (o *SetChargingProfile) GetResponseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResponseUrl
}

// GetResponseUrlOk returns a tuple with the ResponseUrl field value
// and a boolean to check if the value has been set.
func (o *SetChargingProfile) GetResponseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResponseUrl, true
}

// SetResponseUrl sets field value
func (o *SetChargingProfile) SetResponseUrl(v string) {
	o.ResponseUrl = v
}

func (o SetChargingProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetChargingProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["charging_profile"] = o.ChargingProfile
	toSerialize["response_url"] = o.ResponseUrl
	return toSerialize, nil
}

type NullableSetChargingProfile struct {
	value *SetChargingProfile
	isSet bool
}

func (v NullableSetChargingProfile) Get() *SetChargingProfile {
	return v.value
}

func (v *NullableSetChargingProfile) Set(val *SetChargingProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableSetChargingProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableSetChargingProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetChargingProfile(val *SetChargingProfile) *NullableSetChargingProfile {
	return &NullableSetChargingProfile{value: val, isSet: true}
}

func (v NullableSetChargingProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetChargingProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


