/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CredentialsDataRolesBusinessDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialsDataRolesBusinessDetails{}

// CredentialsDataRolesBusinessDetails struct for CredentialsDataRolesBusinessDetails
type CredentialsDataRolesBusinessDetails struct {
	Name string `json:"name"`
	Website *string `json:"website,omitempty"`
	Logo *CredentialsDataRolesBusinessDetailsLogo `json:"logo,omitempty"`
}

// NewCredentialsDataRolesBusinessDetails instantiates a new CredentialsDataRolesBusinessDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialsDataRolesBusinessDetails(name string) *CredentialsDataRolesBusinessDetails {
	this := CredentialsDataRolesBusinessDetails{}
	this.Name = name
	return &this
}

// NewCredentialsDataRolesBusinessDetailsWithDefaults instantiates a new CredentialsDataRolesBusinessDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialsDataRolesBusinessDetailsWithDefaults() *CredentialsDataRolesBusinessDetails {
	this := CredentialsDataRolesBusinessDetails{}
	return &this
}

// GetName returns the Name field value
func (o *CredentialsDataRolesBusinessDetails) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CredentialsDataRolesBusinessDetails) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CredentialsDataRolesBusinessDetails) SetName(v string) {
	o.Name = v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *CredentialsDataRolesBusinessDetails) GetWebsite() string {
	if o == nil || IsNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialsDataRolesBusinessDetails) GetWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Website) {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *CredentialsDataRolesBusinessDetails) HasWebsite() bool {
	if o != nil && !IsNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *CredentialsDataRolesBusinessDetails) SetWebsite(v string) {
	o.Website = &v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *CredentialsDataRolesBusinessDetails) GetLogo() CredentialsDataRolesBusinessDetailsLogo {
	if o == nil || IsNil(o.Logo) {
		var ret CredentialsDataRolesBusinessDetailsLogo
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialsDataRolesBusinessDetails) GetLogoOk() (*CredentialsDataRolesBusinessDetailsLogo, bool) {
	if o == nil || IsNil(o.Logo) {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *CredentialsDataRolesBusinessDetails) HasLogo() bool {
	if o != nil && !IsNil(o.Logo) {
		return true
	}

	return false
}

// SetLogo gets a reference to the given CredentialsDataRolesBusinessDetailsLogo and assigns it to the Logo field.
func (o *CredentialsDataRolesBusinessDetails) SetLogo(v CredentialsDataRolesBusinessDetailsLogo) {
	o.Logo = &v
}

func (o CredentialsDataRolesBusinessDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialsDataRolesBusinessDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	return toSerialize, nil
}

type NullableCredentialsDataRolesBusinessDetails struct {
	value *CredentialsDataRolesBusinessDetails
	isSet bool
}

func (v NullableCredentialsDataRolesBusinessDetails) Get() *CredentialsDataRolesBusinessDetails {
	return v.value
}

func (v *NullableCredentialsDataRolesBusinessDetails) Set(val *CredentialsDataRolesBusinessDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsDataRolesBusinessDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsDataRolesBusinessDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsDataRolesBusinessDetails(val *CredentialsDataRolesBusinessDetails) *NullableCredentialsDataRolesBusinessDetails {
	return &NullableCredentialsDataRolesBusinessDetails{value: val, isSet: true}
}

func (v NullableCredentialsDataRolesBusinessDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsDataRolesBusinessDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


