/*
OCPI CDRs module

Specification for OCPIs CDRs handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrTariffsEnergyMix type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrTariffsEnergyMix{}

// CdrTariffsEnergyMix struct for CdrTariffsEnergyMix
type CdrTariffsEnergyMix struct {
	IsGreenEnergy bool `json:"is_green_energy"`
	EnergySources *CdrTariffsEnergyMixEnergySources `json:"energy_sources,omitempty"`
	EnvironImpact *CdrTariffsEnergyMixEnvironImpact `json:"environ_impact,omitempty"`
	SupplierName *string `json:"supplier_name,omitempty"`
	EnergyProductName *string `json:"energy_product_name,omitempty"`
}

// NewCdrTariffsEnergyMix instantiates a new CdrTariffsEnergyMix object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrTariffsEnergyMix(isGreenEnergy bool) *CdrTariffsEnergyMix {
	this := CdrTariffsEnergyMix{}
	this.IsGreenEnergy = isGreenEnergy
	return &this
}

// NewCdrTariffsEnergyMixWithDefaults instantiates a new CdrTariffsEnergyMix object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrTariffsEnergyMixWithDefaults() *CdrTariffsEnergyMix {
	this := CdrTariffsEnergyMix{}
	return &this
}

// GetIsGreenEnergy returns the IsGreenEnergy field value
func (o *CdrTariffsEnergyMix) GetIsGreenEnergy() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsGreenEnergy
}

// GetIsGreenEnergyOk returns a tuple with the IsGreenEnergy field value
// and a boolean to check if the value has been set.
func (o *CdrTariffsEnergyMix) GetIsGreenEnergyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsGreenEnergy, true
}

// SetIsGreenEnergy sets field value
func (o *CdrTariffsEnergyMix) SetIsGreenEnergy(v bool) {
	o.IsGreenEnergy = v
}

// GetEnergySources returns the EnergySources field value if set, zero value otherwise.
func (o *CdrTariffsEnergyMix) GetEnergySources() CdrTariffsEnergyMixEnergySources {
	if o == nil || IsNil(o.EnergySources) {
		var ret CdrTariffsEnergyMixEnergySources
		return ret
	}
	return *o.EnergySources
}

// GetEnergySourcesOk returns a tuple with the EnergySources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffsEnergyMix) GetEnergySourcesOk() (*CdrTariffsEnergyMixEnergySources, bool) {
	if o == nil || IsNil(o.EnergySources) {
		return nil, false
	}
	return o.EnergySources, true
}

// HasEnergySources returns a boolean if a field has been set.
func (o *CdrTariffsEnergyMix) HasEnergySources() bool {
	if o != nil && !IsNil(o.EnergySources) {
		return true
	}

	return false
}

// SetEnergySources gets a reference to the given CdrTariffsEnergyMixEnergySources and assigns it to the EnergySources field.
func (o *CdrTariffsEnergyMix) SetEnergySources(v CdrTariffsEnergyMixEnergySources) {
	o.EnergySources = &v
}

// GetEnvironImpact returns the EnvironImpact field value if set, zero value otherwise.
func (o *CdrTariffsEnergyMix) GetEnvironImpact() CdrTariffsEnergyMixEnvironImpact {
	if o == nil || IsNil(o.EnvironImpact) {
		var ret CdrTariffsEnergyMixEnvironImpact
		return ret
	}
	return *o.EnvironImpact
}

// GetEnvironImpactOk returns a tuple with the EnvironImpact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffsEnergyMix) GetEnvironImpactOk() (*CdrTariffsEnergyMixEnvironImpact, bool) {
	if o == nil || IsNil(o.EnvironImpact) {
		return nil, false
	}
	return o.EnvironImpact, true
}

// HasEnvironImpact returns a boolean if a field has been set.
func (o *CdrTariffsEnergyMix) HasEnvironImpact() bool {
	if o != nil && !IsNil(o.EnvironImpact) {
		return true
	}

	return false
}

// SetEnvironImpact gets a reference to the given CdrTariffsEnergyMixEnvironImpact and assigns it to the EnvironImpact field.
func (o *CdrTariffsEnergyMix) SetEnvironImpact(v CdrTariffsEnergyMixEnvironImpact) {
	o.EnvironImpact = &v
}

// GetSupplierName returns the SupplierName field value if set, zero value otherwise.
func (o *CdrTariffsEnergyMix) GetSupplierName() string {
	if o == nil || IsNil(o.SupplierName) {
		var ret string
		return ret
	}
	return *o.SupplierName
}

// GetSupplierNameOk returns a tuple with the SupplierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffsEnergyMix) GetSupplierNameOk() (*string, bool) {
	if o == nil || IsNil(o.SupplierName) {
		return nil, false
	}
	return o.SupplierName, true
}

// HasSupplierName returns a boolean if a field has been set.
func (o *CdrTariffsEnergyMix) HasSupplierName() bool {
	if o != nil && !IsNil(o.SupplierName) {
		return true
	}

	return false
}

// SetSupplierName gets a reference to the given string and assigns it to the SupplierName field.
func (o *CdrTariffsEnergyMix) SetSupplierName(v string) {
	o.SupplierName = &v
}

// GetEnergyProductName returns the EnergyProductName field value if set, zero value otherwise.
func (o *CdrTariffsEnergyMix) GetEnergyProductName() string {
	if o == nil || IsNil(o.EnergyProductName) {
		var ret string
		return ret
	}
	return *o.EnergyProductName
}

// GetEnergyProductNameOk returns a tuple with the EnergyProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrTariffsEnergyMix) GetEnergyProductNameOk() (*string, bool) {
	if o == nil || IsNil(o.EnergyProductName) {
		return nil, false
	}
	return o.EnergyProductName, true
}

// HasEnergyProductName returns a boolean if a field has been set.
func (o *CdrTariffsEnergyMix) HasEnergyProductName() bool {
	if o != nil && !IsNil(o.EnergyProductName) {
		return true
	}

	return false
}

// SetEnergyProductName gets a reference to the given string and assigns it to the EnergyProductName field.
func (o *CdrTariffsEnergyMix) SetEnergyProductName(v string) {
	o.EnergyProductName = &v
}

func (o CdrTariffsEnergyMix) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrTariffsEnergyMix) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["is_green_energy"] = o.IsGreenEnergy
	if !IsNil(o.EnergySources) {
		toSerialize["energy_sources"] = o.EnergySources
	}
	if !IsNil(o.EnvironImpact) {
		toSerialize["environ_impact"] = o.EnvironImpact
	}
	if !IsNil(o.SupplierName) {
		toSerialize["supplier_name"] = o.SupplierName
	}
	if !IsNil(o.EnergyProductName) {
		toSerialize["energy_product_name"] = o.EnergyProductName
	}
	return toSerialize, nil
}

type NullableCdrTariffsEnergyMix struct {
	value *CdrTariffsEnergyMix
	isSet bool
}

func (v NullableCdrTariffsEnergyMix) Get() *CdrTariffsEnergyMix {
	return v.value
}

func (v *NullableCdrTariffsEnergyMix) Set(val *CdrTariffsEnergyMix) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrTariffsEnergyMix) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrTariffsEnergyMix) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrTariffsEnergyMix(val *CdrTariffsEnergyMix) *NullableCdrTariffsEnergyMix {
	return &NullableCdrTariffsEnergyMix{value: val, isSet: true}
}

func (v NullableCdrTariffsEnergyMix) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrTariffsEnergyMix) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


