/*
OCPI hub client info module

Specification for OCPIs hub client info handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the ClientInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientInfo{}

// ClientInfo struct for ClientInfo
type ClientInfo struct {
	PartyId string `json:"party_id"`
	CountryCode string `json:"country_code"`
	Role string `json:"role"`
	Status string `json:"status"`
	LastUpdated string `json:"last_updated"`
}

// NewClientInfo instantiates a new ClientInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientInfo(partyId string, countryCode string, role string, status string, lastUpdated string) *ClientInfo {
	this := ClientInfo{}
	this.PartyId = partyId
	this.CountryCode = countryCode
	this.Role = role
	this.Status = status
	this.LastUpdated = lastUpdated
	return &this
}

// NewClientInfoWithDefaults instantiates a new ClientInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientInfoWithDefaults() *ClientInfo {
	this := ClientInfo{}
	return &this
}

// GetPartyId returns the PartyId field value
func (o *ClientInfo) GetPartyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartyId
}

// GetPartyIdOk returns a tuple with the PartyId field value
// and a boolean to check if the value has been set.
func (o *ClientInfo) GetPartyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartyId, true
}

// SetPartyId sets field value
func (o *ClientInfo) SetPartyId(v string) {
	o.PartyId = v
}

// GetCountryCode returns the CountryCode field value
func (o *ClientInfo) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *ClientInfo) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *ClientInfo) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetRole returns the Role field value
func (o *ClientInfo) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ClientInfo) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ClientInfo) SetRole(v string) {
	o.Role = v
}

// GetStatus returns the Status field value
func (o *ClientInfo) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ClientInfo) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ClientInfo) SetStatus(v string) {
	o.Status = v
}

// GetLastUpdated returns the LastUpdated field value
func (o *ClientInfo) GetLastUpdated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
func (o *ClientInfo) GetLastUpdatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdated, true
}

// SetLastUpdated sets field value
func (o *ClientInfo) SetLastUpdated(v string) {
	o.LastUpdated = v
}

func (o ClientInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["party_id"] = o.PartyId
	toSerialize["country_code"] = o.CountryCode
	toSerialize["role"] = o.Role
	toSerialize["status"] = o.Status
	toSerialize["last_updated"] = o.LastUpdated
	return toSerialize, nil
}

type NullableClientInfo struct {
	value *ClientInfo
	isSet bool
}

func (v NullableClientInfo) Get() *ClientInfo {
	return v.value
}

func (v *NullableClientInfo) Set(val *ClientInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableClientInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableClientInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientInfo(val *ClientInfo) *NullableClientInfo {
	return &NullableClientInfo{value: val, isSet: true}
}

func (v NullableClientInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


