/*
OCPI locations module

Specification for OCPIs locations handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the LocationsDataOpeningTimesRegularHours type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocationsDataOpeningTimesRegularHours{}

// LocationsDataOpeningTimesRegularHours struct for LocationsDataOpeningTimesRegularHours
type LocationsDataOpeningTimesRegularHours struct {
	Weekday int32 `json:"weekday"`
	PeriodBegin string `json:"period_begin"`
	PeriodEnd string `json:"period_end"`
}

// NewLocationsDataOpeningTimesRegularHours instantiates a new LocationsDataOpeningTimesRegularHours object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocationsDataOpeningTimesRegularHours(weekday int32, periodBegin string, periodEnd string) *LocationsDataOpeningTimesRegularHours {
	this := LocationsDataOpeningTimesRegularHours{}
	this.Weekday = weekday
	this.PeriodBegin = periodBegin
	this.PeriodEnd = periodEnd
	return &this
}

// NewLocationsDataOpeningTimesRegularHoursWithDefaults instantiates a new LocationsDataOpeningTimesRegularHours object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationsDataOpeningTimesRegularHoursWithDefaults() *LocationsDataOpeningTimesRegularHours {
	this := LocationsDataOpeningTimesRegularHours{}
	return &this
}

// GetWeekday returns the Weekday field value
func (o *LocationsDataOpeningTimesRegularHours) GetWeekday() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Weekday
}

// GetWeekdayOk returns a tuple with the Weekday field value
// and a boolean to check if the value has been set.
func (o *LocationsDataOpeningTimesRegularHours) GetWeekdayOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Weekday, true
}

// SetWeekday sets field value
func (o *LocationsDataOpeningTimesRegularHours) SetWeekday(v int32) {
	o.Weekday = v
}

// GetPeriodBegin returns the PeriodBegin field value
func (o *LocationsDataOpeningTimesRegularHours) GetPeriodBegin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PeriodBegin
}

// GetPeriodBeginOk returns a tuple with the PeriodBegin field value
// and a boolean to check if the value has been set.
func (o *LocationsDataOpeningTimesRegularHours) GetPeriodBeginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PeriodBegin, true
}

// SetPeriodBegin sets field value
func (o *LocationsDataOpeningTimesRegularHours) SetPeriodBegin(v string) {
	o.PeriodBegin = v
}

// GetPeriodEnd returns the PeriodEnd field value
func (o *LocationsDataOpeningTimesRegularHours) GetPeriodEnd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PeriodEnd
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value
// and a boolean to check if the value has been set.
func (o *LocationsDataOpeningTimesRegularHours) GetPeriodEndOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PeriodEnd, true
}

// SetPeriodEnd sets field value
func (o *LocationsDataOpeningTimesRegularHours) SetPeriodEnd(v string) {
	o.PeriodEnd = v
}

func (o LocationsDataOpeningTimesRegularHours) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocationsDataOpeningTimesRegularHours) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["weekday"] = o.Weekday
	toSerialize["period_begin"] = o.PeriodBegin
	toSerialize["period_end"] = o.PeriodEnd
	return toSerialize, nil
}

type NullableLocationsDataOpeningTimesRegularHours struct {
	value *LocationsDataOpeningTimesRegularHours
	isSet bool
}

func (v NullableLocationsDataOpeningTimesRegularHours) Get() *LocationsDataOpeningTimesRegularHours {
	return v.value
}

func (v *NullableLocationsDataOpeningTimesRegularHours) Set(val *LocationsDataOpeningTimesRegularHours) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationsDataOpeningTimesRegularHours) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationsDataOpeningTimesRegularHours) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationsDataOpeningTimesRegularHours(val *LocationsDataOpeningTimesRegularHours) *NullableLocationsDataOpeningTimesRegularHours {
	return &NullableLocationsDataOpeningTimesRegularHours{value: val, isSet: true}
}

func (v NullableLocationsDataOpeningTimesRegularHours) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationsDataOpeningTimesRegularHours) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


