/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrBodyChargingPeriodsDimensions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrBodyChargingPeriodsDimensions{}

// CdrBodyChargingPeriodsDimensions struct for CdrBodyChargingPeriodsDimensions
type CdrBodyChargingPeriodsDimensions struct {
	Type string `json:"type"`
	Volume float32 `json:"volume"`
}

// NewCdrBodyChargingPeriodsDimensions instantiates a new CdrBodyChargingPeriodsDimensions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrBodyChargingPeriodsDimensions(type_ string, volume float32) *CdrBodyChargingPeriodsDimensions {
	this := CdrBodyChargingPeriodsDimensions{}
	this.Type = type_
	this.Volume = volume
	return &this
}

// NewCdrBodyChargingPeriodsDimensionsWithDefaults instantiates a new CdrBodyChargingPeriodsDimensions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrBodyChargingPeriodsDimensionsWithDefaults() *CdrBodyChargingPeriodsDimensions {
	this := CdrBodyChargingPeriodsDimensions{}
	return &this
}

// GetType returns the Type field value
func (o *CdrBodyChargingPeriodsDimensions) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CdrBodyChargingPeriodsDimensions) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CdrBodyChargingPeriodsDimensions) SetType(v string) {
	o.Type = v
}

// GetVolume returns the Volume field value
func (o *CdrBodyChargingPeriodsDimensions) GetVolume() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value
// and a boolean to check if the value has been set.
func (o *CdrBodyChargingPeriodsDimensions) GetVolumeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Volume, true
}

// SetVolume sets field value
func (o *CdrBodyChargingPeriodsDimensions) SetVolume(v float32) {
	o.Volume = v
}

func (o CdrBodyChargingPeriodsDimensions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrBodyChargingPeriodsDimensions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["volume"] = o.Volume
	return toSerialize, nil
}

type NullableCdrBodyChargingPeriodsDimensions struct {
	value *CdrBodyChargingPeriodsDimensions
	isSet bool
}

func (v NullableCdrBodyChargingPeriodsDimensions) Get() *CdrBodyChargingPeriodsDimensions {
	return v.value
}

func (v *NullableCdrBodyChargingPeriodsDimensions) Set(val *CdrBodyChargingPeriodsDimensions) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrBodyChargingPeriodsDimensions) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrBodyChargingPeriodsDimensions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrBodyChargingPeriodsDimensions(val *CdrBodyChargingPeriodsDimensions) *NullableCdrBodyChargingPeriodsDimensions {
	return &NullableCdrBodyChargingPeriodsDimensions{value: val, isSet: true}
}

func (v NullableCdrBodyChargingPeriodsDimensions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrBodyChargingPeriodsDimensions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


