/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the VersionsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VersionsData{}

// VersionsData struct for VersionsData
type VersionsData struct {
	Version string `json:"version"`
	Url string `json:"url"`
}

// NewVersionsData instantiates a new VersionsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVersionsData(version string, url string) *VersionsData {
	this := VersionsData{}
	this.Version = version
	this.Url = url
	return &this
}

// NewVersionsDataWithDefaults instantiates a new VersionsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVersionsDataWithDefaults() *VersionsData {
	this := VersionsData{}
	return &this
}

// GetVersion returns the Version field value
func (o *VersionsData) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *VersionsData) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *VersionsData) SetVersion(v string) {
	o.Version = v
}

// GetUrl returns the Url field value
func (o *VersionsData) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *VersionsData) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *VersionsData) SetUrl(v string) {
	o.Url = v
}

func (o VersionsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VersionsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

type NullableVersionsData struct {
	value *VersionsData
	isSet bool
}

func (v NullableVersionsData) Get() *VersionsData {
	return v.value
}

func (v *NullableVersionsData) Set(val *VersionsData) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionsData) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionsData(val *VersionsData) *NullableVersionsData {
	return &NullableVersionsData{value: val, isSet: true}
}

func (v NullableVersionsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


