/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the Token type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Token{}

// Token struct for Token
type Token struct {
	CountryCode string `json:"country_code"`
	PartyId string `json:"party_id"`
	Uid string `json:"uid"`
	Type string `json:"type"`
	ContractId string `json:"contract_id"`
	VisualNumber *string `json:"visual_number,omitempty"`
	Issuer string `json:"issuer"`
	GroupId *string `json:"group_id,omitempty"`
	Valid bool `json:"valid"`
	Whitelist string `json:"whitelist"`
	Language *string `json:"language,omitempty"`
	DefaultProfileType *string `json:"default_profile_type,omitempty"`
	EnergyContract *TokenEnergyContract `json:"energy_contract,omitempty"`
	LastUpdated string `json:"last_updated"`
}

// NewToken instantiates a new Token object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToken(countryCode string, partyId string, uid string, type_ string, contractId string, issuer string, valid bool, whitelist string, lastUpdated string) *Token {
	this := Token{}
	this.CountryCode = countryCode
	this.PartyId = partyId
	this.Uid = uid
	this.Type = type_
	this.ContractId = contractId
	this.Issuer = issuer
	this.Valid = valid
	this.Whitelist = whitelist
	this.LastUpdated = lastUpdated
	return &this
}

// NewTokenWithDefaults instantiates a new Token object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenWithDefaults() *Token {
	this := Token{}
	return &this
}

// GetCountryCode returns the CountryCode field value
func (o *Token) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *Token) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *Token) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetPartyId returns the PartyId field value
func (o *Token) GetPartyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartyId
}

// GetPartyIdOk returns a tuple with the PartyId field value
// and a boolean to check if the value has been set.
func (o *Token) GetPartyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartyId, true
}

// SetPartyId sets field value
func (o *Token) SetPartyId(v string) {
	o.PartyId = v
}

// GetUid returns the Uid field value
func (o *Token) GetUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *Token) GetUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *Token) SetUid(v string) {
	o.Uid = v
}

// GetType returns the Type field value
func (o *Token) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Token) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Token) SetType(v string) {
	o.Type = v
}

// GetContractId returns the ContractId field value
func (o *Token) GetContractId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value
// and a boolean to check if the value has been set.
func (o *Token) GetContractIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractId, true
}

// SetContractId sets field value
func (o *Token) SetContractId(v string) {
	o.ContractId = v
}

// GetVisualNumber returns the VisualNumber field value if set, zero value otherwise.
func (o *Token) GetVisualNumber() string {
	if o == nil || IsNil(o.VisualNumber) {
		var ret string
		return ret
	}
	return *o.VisualNumber
}

// GetVisualNumberOk returns a tuple with the VisualNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetVisualNumberOk() (*string, bool) {
	if o == nil || IsNil(o.VisualNumber) {
		return nil, false
	}
	return o.VisualNumber, true
}

// HasVisualNumber returns a boolean if a field has been set.
func (o *Token) HasVisualNumber() bool {
	if o != nil && !IsNil(o.VisualNumber) {
		return true
	}

	return false
}

// SetVisualNumber gets a reference to the given string and assigns it to the VisualNumber field.
func (o *Token) SetVisualNumber(v string) {
	o.VisualNumber = &v
}

// GetIssuer returns the Issuer field value
func (o *Token) GetIssuer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value
// and a boolean to check if the value has been set.
func (o *Token) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Issuer, true
}

// SetIssuer sets field value
func (o *Token) SetIssuer(v string) {
	o.Issuer = v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *Token) GetGroupId() string {
	if o == nil || IsNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *Token) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *Token) SetGroupId(v string) {
	o.GroupId = &v
}

// GetValid returns the Valid field value
func (o *Token) GetValid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Valid
}

// GetValidOk returns a tuple with the Valid field value
// and a boolean to check if the value has been set.
func (o *Token) GetValidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Valid, true
}

// SetValid sets field value
func (o *Token) SetValid(v bool) {
	o.Valid = v
}

// GetWhitelist returns the Whitelist field value
func (o *Token) GetWhitelist() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Whitelist
}

// GetWhitelistOk returns a tuple with the Whitelist field value
// and a boolean to check if the value has been set.
func (o *Token) GetWhitelistOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Whitelist, true
}

// SetWhitelist sets field value
func (o *Token) SetWhitelist(v string) {
	o.Whitelist = v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *Token) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *Token) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *Token) SetLanguage(v string) {
	o.Language = &v
}

// GetDefaultProfileType returns the DefaultProfileType field value if set, zero value otherwise.
func (o *Token) GetDefaultProfileType() string {
	if o == nil || IsNil(o.DefaultProfileType) {
		var ret string
		return ret
	}
	return *o.DefaultProfileType
}

// GetDefaultProfileTypeOk returns a tuple with the DefaultProfileType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetDefaultProfileTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultProfileType) {
		return nil, false
	}
	return o.DefaultProfileType, true
}

// HasDefaultProfileType returns a boolean if a field has been set.
func (o *Token) HasDefaultProfileType() bool {
	if o != nil && !IsNil(o.DefaultProfileType) {
		return true
	}

	return false
}

// SetDefaultProfileType gets a reference to the given string and assigns it to the DefaultProfileType field.
func (o *Token) SetDefaultProfileType(v string) {
	o.DefaultProfileType = &v
}

// GetEnergyContract returns the EnergyContract field value if set, zero value otherwise.
func (o *Token) GetEnergyContract() TokenEnergyContract {
	if o == nil || IsNil(o.EnergyContract) {
		var ret TokenEnergyContract
		return ret
	}
	return *o.EnergyContract
}

// GetEnergyContractOk returns a tuple with the EnergyContract field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetEnergyContractOk() (*TokenEnergyContract, bool) {
	if o == nil || IsNil(o.EnergyContract) {
		return nil, false
	}
	return o.EnergyContract, true
}

// HasEnergyContract returns a boolean if a field has been set.
func (o *Token) HasEnergyContract() bool {
	if o != nil && !IsNil(o.EnergyContract) {
		return true
	}

	return false
}

// SetEnergyContract gets a reference to the given TokenEnergyContract and assigns it to the EnergyContract field.
func (o *Token) SetEnergyContract(v TokenEnergyContract) {
	o.EnergyContract = &v
}

// GetLastUpdated returns the LastUpdated field value
func (o *Token) GetLastUpdated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
func (o *Token) GetLastUpdatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdated, true
}

// SetLastUpdated sets field value
func (o *Token) SetLastUpdated(v string) {
	o.LastUpdated = v
}

func (o Token) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Token) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["country_code"] = o.CountryCode
	toSerialize["party_id"] = o.PartyId
	toSerialize["uid"] = o.Uid
	toSerialize["type"] = o.Type
	toSerialize["contract_id"] = o.ContractId
	if !IsNil(o.VisualNumber) {
		toSerialize["visual_number"] = o.VisualNumber
	}
	toSerialize["issuer"] = o.Issuer
	if !IsNil(o.GroupId) {
		toSerialize["group_id"] = o.GroupId
	}
	toSerialize["valid"] = o.Valid
	toSerialize["whitelist"] = o.Whitelist
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !IsNil(o.DefaultProfileType) {
		toSerialize["default_profile_type"] = o.DefaultProfileType
	}
	if !IsNil(o.EnergyContract) {
		toSerialize["energy_contract"] = o.EnergyContract
	}
	toSerialize["last_updated"] = o.LastUpdated
	return toSerialize, nil
}

type NullableToken struct {
	value *Token
	isSet bool
}

func (v NullableToken) Get() *Token {
	return v.value
}

func (v *NullableToken) Set(val *Token) {
	v.value = val
	v.isSet = true
}

func (v NullableToken) IsSet() bool {
	return v.isSet
}

func (v *NullableToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToken(val *Token) *NullableToken {
	return &NullableToken{value: val, isSet: true}
}

func (v NullableToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


