/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the Price type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Price{}

// Price struct for Price
type Price struct {
	ExclVat float32 `json:"excl_vat"`
	InclVat *float32 `json:"incl_vat,omitempty"`
}

// NewPrice instantiates a new Price object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrice(exclVat float32) *Price {
	this := Price{}
	this.ExclVat = exclVat
	return &this
}

// NewPriceWithDefaults instantiates a new Price object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceWithDefaults() *Price {
	this := Price{}
	return &this
}

// GetExclVat returns the ExclVat field value
func (o *Price) GetExclVat() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ExclVat
}

// GetExclVatOk returns a tuple with the ExclVat field value
// and a boolean to check if the value has been set.
func (o *Price) GetExclVatOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExclVat, true
}

// SetExclVat sets field value
func (o *Price) SetExclVat(v float32) {
	o.ExclVat = v
}

// GetInclVat returns the InclVat field value if set, zero value otherwise.
func (o *Price) GetInclVat() float32 {
	if o == nil || IsNil(o.InclVat) {
		var ret float32
		return ret
	}
	return *o.InclVat
}

// GetInclVatOk returns a tuple with the InclVat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Price) GetInclVatOk() (*float32, bool) {
	if o == nil || IsNil(o.InclVat) {
		return nil, false
	}
	return o.InclVat, true
}

// HasInclVat returns a boolean if a field has been set.
func (o *Price) HasInclVat() bool {
	if o != nil && !IsNil(o.InclVat) {
		return true
	}

	return false
}

// SetInclVat gets a reference to the given float32 and assigns it to the InclVat field.
func (o *Price) SetInclVat(v float32) {
	o.InclVat = &v
}

func (o Price) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Price) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["excl_vat"] = o.ExclVat
	if !IsNil(o.InclVat) {
		toSerialize["incl_vat"] = o.InclVat
	}
	return toSerialize, nil
}

type NullablePrice struct {
	value *Price
	isSet bool
}

func (v NullablePrice) Get() *Price {
	return v.value
}

func (v *NullablePrice) Set(val *Price) {
	v.value = val
	v.isSet = true
}

func (v NullablePrice) IsSet() bool {
	return v.isSet
}

func (v *NullablePrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrice(val *Price) *NullablePrice {
	return &NullablePrice{value: val, isSet: true}
}

func (v NullablePrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


