/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the ChargingProfilesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChargingProfilesResponse{}

// ChargingProfilesResponse struct for ChargingProfilesResponse
type ChargingProfilesResponse struct {
	ChargingProfile *ChargingProfileResponse `json:"chargingProfile,omitempty"`
	StatusCode float32 `json:"status_code"`
	StatusMessage *string `json:"status_message,omitempty"`
	TimeStamp *string `json:"timeStamp,omitempty"`
}

// NewChargingProfilesResponse instantiates a new ChargingProfilesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChargingProfilesResponse(statusCode float32) *ChargingProfilesResponse {
	this := ChargingProfilesResponse{}
	this.StatusCode = statusCode
	return &this
}

// NewChargingProfilesResponseWithDefaults instantiates a new ChargingProfilesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChargingProfilesResponseWithDefaults() *ChargingProfilesResponse {
	this := ChargingProfilesResponse{}
	return &this
}

// GetChargingProfile returns the ChargingProfile field value if set, zero value otherwise.
func (o *ChargingProfilesResponse) GetChargingProfile() ChargingProfileResponse {
	if o == nil || IsNil(o.ChargingProfile) {
		var ret ChargingProfileResponse
		return ret
	}
	return *o.ChargingProfile
}

// GetChargingProfileOk returns a tuple with the ChargingProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargingProfilesResponse) GetChargingProfileOk() (*ChargingProfileResponse, bool) {
	if o == nil || IsNil(o.ChargingProfile) {
		return nil, false
	}
	return o.ChargingProfile, true
}

// HasChargingProfile returns a boolean if a field has been set.
func (o *ChargingProfilesResponse) HasChargingProfile() bool {
	if o != nil && !IsNil(o.ChargingProfile) {
		return true
	}

	return false
}

// SetChargingProfile gets a reference to the given ChargingProfileResponse and assigns it to the ChargingProfile field.
func (o *ChargingProfilesResponse) SetChargingProfile(v ChargingProfileResponse) {
	o.ChargingProfile = &v
}

// GetStatusCode returns the StatusCode field value
func (o *ChargingProfilesResponse) GetStatusCode() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *ChargingProfilesResponse) GetStatusCodeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *ChargingProfilesResponse) SetStatusCode(v float32) {
	o.StatusCode = v
}

// GetStatusMessage returns the StatusMessage field value if set, zero value otherwise.
func (o *ChargingProfilesResponse) GetStatusMessage() string {
	if o == nil || IsNil(o.StatusMessage) {
		var ret string
		return ret
	}
	return *o.StatusMessage
}

// GetStatusMessageOk returns a tuple with the StatusMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargingProfilesResponse) GetStatusMessageOk() (*string, bool) {
	if o == nil || IsNil(o.StatusMessage) {
		return nil, false
	}
	return o.StatusMessage, true
}

// HasStatusMessage returns a boolean if a field has been set.
func (o *ChargingProfilesResponse) HasStatusMessage() bool {
	if o != nil && !IsNil(o.StatusMessage) {
		return true
	}

	return false
}

// SetStatusMessage gets a reference to the given string and assigns it to the StatusMessage field.
func (o *ChargingProfilesResponse) SetStatusMessage(v string) {
	o.StatusMessage = &v
}

// GetTimeStamp returns the TimeStamp field value if set, zero value otherwise.
func (o *ChargingProfilesResponse) GetTimeStamp() string {
	if o == nil || IsNil(o.TimeStamp) {
		var ret string
		return ret
	}
	return *o.TimeStamp
}

// GetTimeStampOk returns a tuple with the TimeStamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargingProfilesResponse) GetTimeStampOk() (*string, bool) {
	if o == nil || IsNil(o.TimeStamp) {
		return nil, false
	}
	return o.TimeStamp, true
}

// HasTimeStamp returns a boolean if a field has been set.
func (o *ChargingProfilesResponse) HasTimeStamp() bool {
	if o != nil && !IsNil(o.TimeStamp) {
		return true
	}

	return false
}

// SetTimeStamp gets a reference to the given string and assigns it to the TimeStamp field.
func (o *ChargingProfilesResponse) SetTimeStamp(v string) {
	o.TimeStamp = &v
}

func (o ChargingProfilesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChargingProfilesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChargingProfile) {
		toSerialize["chargingProfile"] = o.ChargingProfile
	}
	toSerialize["status_code"] = o.StatusCode
	if !IsNil(o.StatusMessage) {
		toSerialize["status_message"] = o.StatusMessage
	}
	if !IsNil(o.TimeStamp) {
		toSerialize["timeStamp"] = o.TimeStamp
	}
	return toSerialize, nil
}

type NullableChargingProfilesResponse struct {
	value *ChargingProfilesResponse
	isSet bool
}

func (v NullableChargingProfilesResponse) Get() *ChargingProfilesResponse {
	return v.value
}

func (v *NullableChargingProfilesResponse) Set(val *ChargingProfilesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChargingProfilesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChargingProfilesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChargingProfilesResponse(val *ChargingProfilesResponse) *NullableChargingProfilesResponse {
	return &NullableChargingProfilesResponse{value: val, isSet: true}
}

func (v NullableChargingProfilesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChargingProfilesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


