/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrBodyCdrToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrBodyCdrToken{}

// CdrBodyCdrToken struct for CdrBodyCdrToken
type CdrBodyCdrToken struct {
	CountryCode string `json:"country_code"`
	PartyId string `json:"party_id"`
	Uid string `json:"uid"`
	Type string `json:"type"`
	ContractId string `json:"contract_id"`
}

// NewCdrBodyCdrToken instantiates a new CdrBodyCdrToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrBodyCdrToken(countryCode string, partyId string, uid string, type_ string, contractId string) *CdrBodyCdrToken {
	this := CdrBodyCdrToken{}
	this.CountryCode = countryCode
	this.PartyId = partyId
	this.Uid = uid
	this.Type = type_
	this.ContractId = contractId
	return &this
}

// NewCdrBodyCdrTokenWithDefaults instantiates a new CdrBodyCdrToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrBodyCdrTokenWithDefaults() *CdrBodyCdrToken {
	this := CdrBodyCdrToken{}
	return &this
}

// GetCountryCode returns the CountryCode field value
func (o *CdrBodyCdrToken) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *CdrBodyCdrToken) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *CdrBodyCdrToken) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetPartyId returns the PartyId field value
func (o *CdrBodyCdrToken) GetPartyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartyId
}

// GetPartyIdOk returns a tuple with the PartyId field value
// and a boolean to check if the value has been set.
func (o *CdrBodyCdrToken) GetPartyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartyId, true
}

// SetPartyId sets field value
func (o *CdrBodyCdrToken) SetPartyId(v string) {
	o.PartyId = v
}

// GetUid returns the Uid field value
func (o *CdrBodyCdrToken) GetUid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *CdrBodyCdrToken) GetUidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *CdrBodyCdrToken) SetUid(v string) {
	o.Uid = v
}

// GetType returns the Type field value
func (o *CdrBodyCdrToken) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CdrBodyCdrToken) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CdrBodyCdrToken) SetType(v string) {
	o.Type = v
}

// GetContractId returns the ContractId field value
func (o *CdrBodyCdrToken) GetContractId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value
// and a boolean to check if the value has been set.
func (o *CdrBodyCdrToken) GetContractIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractId, true
}

// SetContractId sets field value
func (o *CdrBodyCdrToken) SetContractId(v string) {
	o.ContractId = v
}

func (o CdrBodyCdrToken) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrBodyCdrToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["country_code"] = o.CountryCode
	toSerialize["party_id"] = o.PartyId
	toSerialize["uid"] = o.Uid
	toSerialize["type"] = o.Type
	toSerialize["contract_id"] = o.ContractId
	return toSerialize, nil
}

type NullableCdrBodyCdrToken struct {
	value *CdrBodyCdrToken
	isSet bool
}

func (v NullableCdrBodyCdrToken) Get() *CdrBodyCdrToken {
	return v.value
}

func (v *NullableCdrBodyCdrToken) Set(val *CdrBodyCdrToken) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrBodyCdrToken) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrBodyCdrToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrBodyCdrToken(val *CdrBodyCdrToken) *NullableCdrBodyCdrToken {
	return &NullableCdrBodyCdrToken{value: val, isSet: true}
}

func (v NullableCdrBodyCdrToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrBodyCdrToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


