/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrBodyChargingPeriods type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrBodyChargingPeriods{}

// CdrBodyChargingPeriods struct for CdrBodyChargingPeriods
type CdrBodyChargingPeriods struct {
	StartDateTime string `json:"start_date_time"`
	Dimensions *CdrBodyChargingPeriodsDimensions `json:"dimensions,omitempty"`
	TariffId *string `json:"tariff_id,omitempty"`
}

// NewCdrBodyChargingPeriods instantiates a new CdrBodyChargingPeriods object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrBodyChargingPeriods(startDateTime string) *CdrBodyChargingPeriods {
	this := CdrBodyChargingPeriods{}
	this.StartDateTime = startDateTime
	return &this
}

// NewCdrBodyChargingPeriodsWithDefaults instantiates a new CdrBodyChargingPeriods object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrBodyChargingPeriodsWithDefaults() *CdrBodyChargingPeriods {
	this := CdrBodyChargingPeriods{}
	return &this
}

// GetStartDateTime returns the StartDateTime field value
func (o *CdrBodyChargingPeriods) GetStartDateTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartDateTime
}

// GetStartDateTimeOk returns a tuple with the StartDateTime field value
// and a boolean to check if the value has been set.
func (o *CdrBodyChargingPeriods) GetStartDateTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartDateTime, true
}

// SetStartDateTime sets field value
func (o *CdrBodyChargingPeriods) SetStartDateTime(v string) {
	o.StartDateTime = v
}

// GetDimensions returns the Dimensions field value if set, zero value otherwise.
func (o *CdrBodyChargingPeriods) GetDimensions() CdrBodyChargingPeriodsDimensions {
	if o == nil || IsNil(o.Dimensions) {
		var ret CdrBodyChargingPeriodsDimensions
		return ret
	}
	return *o.Dimensions
}

// GetDimensionsOk returns a tuple with the Dimensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodyChargingPeriods) GetDimensionsOk() (*CdrBodyChargingPeriodsDimensions, bool) {
	if o == nil || IsNil(o.Dimensions) {
		return nil, false
	}
	return o.Dimensions, true
}

// HasDimensions returns a boolean if a field has been set.
func (o *CdrBodyChargingPeriods) HasDimensions() bool {
	if o != nil && !IsNil(o.Dimensions) {
		return true
	}

	return false
}

// SetDimensions gets a reference to the given CdrBodyChargingPeriodsDimensions and assigns it to the Dimensions field.
func (o *CdrBodyChargingPeriods) SetDimensions(v CdrBodyChargingPeriodsDimensions) {
	o.Dimensions = &v
}

// GetTariffId returns the TariffId field value if set, zero value otherwise.
func (o *CdrBodyChargingPeriods) GetTariffId() string {
	if o == nil || IsNil(o.TariffId) {
		var ret string
		return ret
	}
	return *o.TariffId
}

// GetTariffIdOk returns a tuple with the TariffId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodyChargingPeriods) GetTariffIdOk() (*string, bool) {
	if o == nil || IsNil(o.TariffId) {
		return nil, false
	}
	return o.TariffId, true
}

// HasTariffId returns a boolean if a field has been set.
func (o *CdrBodyChargingPeriods) HasTariffId() bool {
	if o != nil && !IsNil(o.TariffId) {
		return true
	}

	return false
}

// SetTariffId gets a reference to the given string and assigns it to the TariffId field.
func (o *CdrBodyChargingPeriods) SetTariffId(v string) {
	o.TariffId = &v
}

func (o CdrBodyChargingPeriods) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrBodyChargingPeriods) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start_date_time"] = o.StartDateTime
	if !IsNil(o.Dimensions) {
		toSerialize["dimensions"] = o.Dimensions
	}
	if !IsNil(o.TariffId) {
		toSerialize["tariff_id"] = o.TariffId
	}
	return toSerialize, nil
}

type NullableCdrBodyChargingPeriods struct {
	value *CdrBodyChargingPeriods
	isSet bool
}

func (v NullableCdrBodyChargingPeriods) Get() *CdrBodyChargingPeriods {
	return v.value
}

func (v *NullableCdrBodyChargingPeriods) Set(val *CdrBodyChargingPeriods) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrBodyChargingPeriods) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrBodyChargingPeriods) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrBodyChargingPeriods(val *CdrBodyChargingPeriods) *NullableCdrBodyChargingPeriods {
	return &NullableCdrBodyChargingPeriods{value: val, isSet: true}
}

func (v NullableCdrBodyChargingPeriods) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrBodyChargingPeriods) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


