/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrBodyTariffsElements type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrBodyTariffsElements{}

// CdrBodyTariffsElements struct for CdrBodyTariffsElements
type CdrBodyTariffsElements struct {
	PriceComponents *string `json:"price_components,omitempty"`
	Restrictions *CdrBodyTariffsElementsRestrictions `json:"restrictions,omitempty"`
}

// NewCdrBodyTariffsElements instantiates a new CdrBodyTariffsElements object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrBodyTariffsElements() *CdrBodyTariffsElements {
	this := CdrBodyTariffsElements{}
	return &this
}

// NewCdrBodyTariffsElementsWithDefaults instantiates a new CdrBodyTariffsElements object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrBodyTariffsElementsWithDefaults() *CdrBodyTariffsElements {
	this := CdrBodyTariffsElements{}
	return &this
}

// GetPriceComponents returns the PriceComponents field value if set, zero value otherwise.
func (o *CdrBodyTariffsElements) GetPriceComponents() string {
	if o == nil || IsNil(o.PriceComponents) {
		var ret string
		return ret
	}
	return *o.PriceComponents
}

// GetPriceComponentsOk returns a tuple with the PriceComponents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsElements) GetPriceComponentsOk() (*string, bool) {
	if o == nil || IsNil(o.PriceComponents) {
		return nil, false
	}
	return o.PriceComponents, true
}

// HasPriceComponents returns a boolean if a field has been set.
func (o *CdrBodyTariffsElements) HasPriceComponents() bool {
	if o != nil && !IsNil(o.PriceComponents) {
		return true
	}

	return false
}

// SetPriceComponents gets a reference to the given string and assigns it to the PriceComponents field.
func (o *CdrBodyTariffsElements) SetPriceComponents(v string) {
	o.PriceComponents = &v
}

// GetRestrictions returns the Restrictions field value if set, zero value otherwise.
func (o *CdrBodyTariffsElements) GetRestrictions() CdrBodyTariffsElementsRestrictions {
	if o == nil || IsNil(o.Restrictions) {
		var ret CdrBodyTariffsElementsRestrictions
		return ret
	}
	return *o.Restrictions
}

// GetRestrictionsOk returns a tuple with the Restrictions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsElements) GetRestrictionsOk() (*CdrBodyTariffsElementsRestrictions, bool) {
	if o == nil || IsNil(o.Restrictions) {
		return nil, false
	}
	return o.Restrictions, true
}

// HasRestrictions returns a boolean if a field has been set.
func (o *CdrBodyTariffsElements) HasRestrictions() bool {
	if o != nil && !IsNil(o.Restrictions) {
		return true
	}

	return false
}

// SetRestrictions gets a reference to the given CdrBodyTariffsElementsRestrictions and assigns it to the Restrictions field.
func (o *CdrBodyTariffsElements) SetRestrictions(v CdrBodyTariffsElementsRestrictions) {
	o.Restrictions = &v
}

func (o CdrBodyTariffsElements) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrBodyTariffsElements) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PriceComponents) {
		toSerialize["price_components"] = o.PriceComponents
	}
	if !IsNil(o.Restrictions) {
		toSerialize["restrictions"] = o.Restrictions
	}
	return toSerialize, nil
}

type NullableCdrBodyTariffsElements struct {
	value *CdrBodyTariffsElements
	isSet bool
}

func (v NullableCdrBodyTariffsElements) Get() *CdrBodyTariffsElements {
	return v.value
}

func (v *NullableCdrBodyTariffsElements) Set(val *CdrBodyTariffsElements) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrBodyTariffsElements) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrBodyTariffsElements) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrBodyTariffsElements(val *CdrBodyTariffsElements) *NullableCdrBodyTariffsElements {
	return &NullableCdrBodyTariffsElements{value: val, isSet: true}
}

func (v NullableCdrBodyTariffsElements) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrBodyTariffsElements) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


