/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the ChargingProfileChargingProfilePeriod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChargingProfileChargingProfilePeriod{}

// ChargingProfileChargingProfilePeriod struct for ChargingProfileChargingProfilePeriod
type ChargingProfileChargingProfilePeriod struct {
	StartPeriod int32 `json:"start_period"`
	Limit float32 `json:"limit"`
}

// NewChargingProfileChargingProfilePeriod instantiates a new ChargingProfileChargingProfilePeriod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChargingProfileChargingProfilePeriod(startPeriod int32, limit float32) *ChargingProfileChargingProfilePeriod {
	this := ChargingProfileChargingProfilePeriod{}
	this.StartPeriod = startPeriod
	this.Limit = limit
	return &this
}

// NewChargingProfileChargingProfilePeriodWithDefaults instantiates a new ChargingProfileChargingProfilePeriod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChargingProfileChargingProfilePeriodWithDefaults() *ChargingProfileChargingProfilePeriod {
	this := ChargingProfileChargingProfilePeriod{}
	return &this
}

// GetStartPeriod returns the StartPeriod field value
func (o *ChargingProfileChargingProfilePeriod) GetStartPeriod() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StartPeriod
}

// GetStartPeriodOk returns a tuple with the StartPeriod field value
// and a boolean to check if the value has been set.
func (o *ChargingProfileChargingProfilePeriod) GetStartPeriodOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartPeriod, true
}

// SetStartPeriod sets field value
func (o *ChargingProfileChargingProfilePeriod) SetStartPeriod(v int32) {
	o.StartPeriod = v
}

// GetLimit returns the Limit field value
func (o *ChargingProfileChargingProfilePeriod) GetLimit() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *ChargingProfileChargingProfilePeriod) GetLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *ChargingProfileChargingProfilePeriod) SetLimit(v float32) {
	o.Limit = v
}

func (o ChargingProfileChargingProfilePeriod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChargingProfileChargingProfilePeriod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start_period"] = o.StartPeriod
	toSerialize["limit"] = o.Limit
	return toSerialize, nil
}

type NullableChargingProfileChargingProfilePeriod struct {
	value *ChargingProfileChargingProfilePeriod
	isSet bool
}

func (v NullableChargingProfileChargingProfilePeriod) Get() *ChargingProfileChargingProfilePeriod {
	return v.value
}

func (v *NullableChargingProfileChargingProfilePeriod) Set(val *ChargingProfileChargingProfilePeriod) {
	v.value = val
	v.isSet = true
}

func (v NullableChargingProfileChargingProfilePeriod) IsSet() bool {
	return v.isSet
}

func (v *NullableChargingProfileChargingProfilePeriod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChargingProfileChargingProfilePeriod(val *ChargingProfileChargingProfilePeriod) *NullableChargingProfileChargingProfilePeriod {
	return &NullableChargingProfileChargingProfilePeriod{value: val, isSet: true}
}

func (v NullableChargingProfileChargingProfilePeriod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChargingProfileChargingProfilePeriod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


