/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the TariffEnergyMixEnvironImpact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TariffEnergyMixEnvironImpact{}

// TariffEnergyMixEnvironImpact struct for TariffEnergyMixEnvironImpact
type TariffEnergyMixEnvironImpact struct {
	Category EnvironmentalImpactCategoryType `json:"category"`
	Amount float32 `json:"amount"`
}

// NewTariffEnergyMixEnvironImpact instantiates a new TariffEnergyMixEnvironImpact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTariffEnergyMixEnvironImpact(category EnvironmentalImpactCategoryType, amount float32) *TariffEnergyMixEnvironImpact {
	this := TariffEnergyMixEnvironImpact{}
	this.Category = category
	this.Amount = amount
	return &this
}

// NewTariffEnergyMixEnvironImpactWithDefaults instantiates a new TariffEnergyMixEnvironImpact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTariffEnergyMixEnvironImpactWithDefaults() *TariffEnergyMixEnvironImpact {
	this := TariffEnergyMixEnvironImpact{}
	return &this
}

// GetCategory returns the Category field value
func (o *TariffEnergyMixEnvironImpact) GetCategory() EnvironmentalImpactCategoryType {
	if o == nil {
		var ret EnvironmentalImpactCategoryType
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *TariffEnergyMixEnvironImpact) GetCategoryOk() (*EnvironmentalImpactCategoryType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *TariffEnergyMixEnvironImpact) SetCategory(v EnvironmentalImpactCategoryType) {
	o.Category = v
}

// GetAmount returns the Amount field value
func (o *TariffEnergyMixEnvironImpact) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TariffEnergyMixEnvironImpact) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TariffEnergyMixEnvironImpact) SetAmount(v float32) {
	o.Amount = v
}

func (o TariffEnergyMixEnvironImpact) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TariffEnergyMixEnvironImpact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["category"] = o.Category
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

type NullableTariffEnergyMixEnvironImpact struct {
	value *TariffEnergyMixEnvironImpact
	isSet bool
}

func (v NullableTariffEnergyMixEnvironImpact) Get() *TariffEnergyMixEnvironImpact {
	return v.value
}

func (v *NullableTariffEnergyMixEnvironImpact) Set(val *TariffEnergyMixEnvironImpact) {
	v.value = val
	v.isSet = true
}

func (v NullableTariffEnergyMixEnvironImpact) IsSet() bool {
	return v.isSet
}

func (v *NullableTariffEnergyMixEnvironImpact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTariffEnergyMixEnvironImpact(val *TariffEnergyMixEnvironImpact) *NullableTariffEnergyMixEnvironImpact {
	return &NullableTariffEnergyMixEnvironImpact{value: val, isSet: true}
}

func (v NullableTariffEnergyMixEnvironImpact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTariffEnergyMixEnvironImpact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


