/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrBodySignedData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrBodySignedData{}

// CdrBodySignedData struct for CdrBodySignedData
type CdrBodySignedData struct {
	EncodingMethod string `json:"encoding_method"`
	EncodingMethodVersion *int32 `json:"encoding_method_version,omitempty"`
	PublicKey *string `json:"public_key,omitempty"`
	SignedValues *CdrBodySignedDataSignedValues `json:"signed_values,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewCdrBodySignedData instantiates a new CdrBodySignedData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrBodySignedData(encodingMethod string) *CdrBodySignedData {
	this := CdrBodySignedData{}
	this.EncodingMethod = encodingMethod
	return &this
}

// NewCdrBodySignedDataWithDefaults instantiates a new CdrBodySignedData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrBodySignedDataWithDefaults() *CdrBodySignedData {
	this := CdrBodySignedData{}
	return &this
}

// GetEncodingMethod returns the EncodingMethod field value
func (o *CdrBodySignedData) GetEncodingMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EncodingMethod
}

// GetEncodingMethodOk returns a tuple with the EncodingMethod field value
// and a boolean to check if the value has been set.
func (o *CdrBodySignedData) GetEncodingMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EncodingMethod, true
}

// SetEncodingMethod sets field value
func (o *CdrBodySignedData) SetEncodingMethod(v string) {
	o.EncodingMethod = v
}

// GetEncodingMethodVersion returns the EncodingMethodVersion field value if set, zero value otherwise.
func (o *CdrBodySignedData) GetEncodingMethodVersion() int32 {
	if o == nil || IsNil(o.EncodingMethodVersion) {
		var ret int32
		return ret
	}
	return *o.EncodingMethodVersion
}

// GetEncodingMethodVersionOk returns a tuple with the EncodingMethodVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodySignedData) GetEncodingMethodVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.EncodingMethodVersion) {
		return nil, false
	}
	return o.EncodingMethodVersion, true
}

// HasEncodingMethodVersion returns a boolean if a field has been set.
func (o *CdrBodySignedData) HasEncodingMethodVersion() bool {
	if o != nil && !IsNil(o.EncodingMethodVersion) {
		return true
	}

	return false
}

// SetEncodingMethodVersion gets a reference to the given int32 and assigns it to the EncodingMethodVersion field.
func (o *CdrBodySignedData) SetEncodingMethodVersion(v int32) {
	o.EncodingMethodVersion = &v
}

// GetPublicKey returns the PublicKey field value if set, zero value otherwise.
func (o *CdrBodySignedData) GetPublicKey() string {
	if o == nil || IsNil(o.PublicKey) {
		var ret string
		return ret
	}
	return *o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodySignedData) GetPublicKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PublicKey) {
		return nil, false
	}
	return o.PublicKey, true
}

// HasPublicKey returns a boolean if a field has been set.
func (o *CdrBodySignedData) HasPublicKey() bool {
	if o != nil && !IsNil(o.PublicKey) {
		return true
	}

	return false
}

// SetPublicKey gets a reference to the given string and assigns it to the PublicKey field.
func (o *CdrBodySignedData) SetPublicKey(v string) {
	o.PublicKey = &v
}

// GetSignedValues returns the SignedValues field value if set, zero value otherwise.
func (o *CdrBodySignedData) GetSignedValues() CdrBodySignedDataSignedValues {
	if o == nil || IsNil(o.SignedValues) {
		var ret CdrBodySignedDataSignedValues
		return ret
	}
	return *o.SignedValues
}

// GetSignedValuesOk returns a tuple with the SignedValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodySignedData) GetSignedValuesOk() (*CdrBodySignedDataSignedValues, bool) {
	if o == nil || IsNil(o.SignedValues) {
		return nil, false
	}
	return o.SignedValues, true
}

// HasSignedValues returns a boolean if a field has been set.
func (o *CdrBodySignedData) HasSignedValues() bool {
	if o != nil && !IsNil(o.SignedValues) {
		return true
	}

	return false
}

// SetSignedValues gets a reference to the given CdrBodySignedDataSignedValues and assigns it to the SignedValues field.
func (o *CdrBodySignedData) SetSignedValues(v CdrBodySignedDataSignedValues) {
	o.SignedValues = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *CdrBodySignedData) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdrBodySignedData) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *CdrBodySignedData) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *CdrBodySignedData) SetUrl(v string) {
	o.Url = &v
}

func (o CdrBodySignedData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrBodySignedData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["encoding_method"] = o.EncodingMethod
	if !IsNil(o.EncodingMethodVersion) {
		toSerialize["encoding_method_version"] = o.EncodingMethodVersion
	}
	if !IsNil(o.PublicKey) {
		toSerialize["public_key"] = o.PublicKey
	}
	if !IsNil(o.SignedValues) {
		toSerialize["signed_values"] = o.SignedValues
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableCdrBodySignedData struct {
	value *CdrBodySignedData
	isSet bool
}

func (v NullableCdrBodySignedData) Get() *CdrBodySignedData {
	return v.value
}

func (v *NullableCdrBodySignedData) Set(val *CdrBodySignedData) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrBodySignedData) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrBodySignedData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrBodySignedData(val *CdrBodySignedData) *NullableCdrBodySignedData {
	return &NullableCdrBodySignedData{value: val, isSet: true}
}

func (v NullableCdrBodySignedData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrBodySignedData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


