/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the LocationsDataOpeningTimesExceptionalOpenings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocationsDataOpeningTimesExceptionalOpenings{}

// LocationsDataOpeningTimesExceptionalOpenings struct for LocationsDataOpeningTimesExceptionalOpenings
type LocationsDataOpeningTimesExceptionalOpenings struct {
	PeriodBegin string `json:"period_begin"`
	PeriodEnd string `json:"period_end"`
}

// NewLocationsDataOpeningTimesExceptionalOpenings instantiates a new LocationsDataOpeningTimesExceptionalOpenings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocationsDataOpeningTimesExceptionalOpenings(periodBegin string, periodEnd string) *LocationsDataOpeningTimesExceptionalOpenings {
	this := LocationsDataOpeningTimesExceptionalOpenings{}
	this.PeriodBegin = periodBegin
	this.PeriodEnd = periodEnd
	return &this
}

// NewLocationsDataOpeningTimesExceptionalOpeningsWithDefaults instantiates a new LocationsDataOpeningTimesExceptionalOpenings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationsDataOpeningTimesExceptionalOpeningsWithDefaults() *LocationsDataOpeningTimesExceptionalOpenings {
	this := LocationsDataOpeningTimesExceptionalOpenings{}
	return &this
}

// GetPeriodBegin returns the PeriodBegin field value
func (o *LocationsDataOpeningTimesExceptionalOpenings) GetPeriodBegin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PeriodBegin
}

// GetPeriodBeginOk returns a tuple with the PeriodBegin field value
// and a boolean to check if the value has been set.
func (o *LocationsDataOpeningTimesExceptionalOpenings) GetPeriodBeginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PeriodBegin, true
}

// SetPeriodBegin sets field value
func (o *LocationsDataOpeningTimesExceptionalOpenings) SetPeriodBegin(v string) {
	o.PeriodBegin = v
}

// GetPeriodEnd returns the PeriodEnd field value
func (o *LocationsDataOpeningTimesExceptionalOpenings) GetPeriodEnd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PeriodEnd
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value
// and a boolean to check if the value has been set.
func (o *LocationsDataOpeningTimesExceptionalOpenings) GetPeriodEndOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PeriodEnd, true
}

// SetPeriodEnd sets field value
func (o *LocationsDataOpeningTimesExceptionalOpenings) SetPeriodEnd(v string) {
	o.PeriodEnd = v
}

func (o LocationsDataOpeningTimesExceptionalOpenings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocationsDataOpeningTimesExceptionalOpenings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["period_begin"] = o.PeriodBegin
	toSerialize["period_end"] = o.PeriodEnd
	return toSerialize, nil
}

type NullableLocationsDataOpeningTimesExceptionalOpenings struct {
	value *LocationsDataOpeningTimesExceptionalOpenings
	isSet bool
}

func (v NullableLocationsDataOpeningTimesExceptionalOpenings) Get() *LocationsDataOpeningTimesExceptionalOpenings {
	return v.value
}

func (v *NullableLocationsDataOpeningTimesExceptionalOpenings) Set(val *LocationsDataOpeningTimesExceptionalOpenings) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationsDataOpeningTimesExceptionalOpenings) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationsDataOpeningTimesExceptionalOpenings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationsDataOpeningTimesExceptionalOpenings(val *LocationsDataOpeningTimesExceptionalOpenings) *NullableLocationsDataOpeningTimesExceptionalOpenings {
	return &NullableLocationsDataOpeningTimesExceptionalOpenings{value: val, isSet: true}
}

func (v NullableLocationsDataOpeningTimesExceptionalOpenings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationsDataOpeningTimesExceptionalOpenings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


