/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrBodyTariffsEnergyMixEnvironImpact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrBodyTariffsEnergyMixEnvironImpact{}

// CdrBodyTariffsEnergyMixEnvironImpact struct for CdrBodyTariffsEnergyMixEnvironImpact
type CdrBodyTariffsEnergyMixEnvironImpact struct {
	Category string `json:"category"`
	Amount float32 `json:"amount"`
}

// NewCdrBodyTariffsEnergyMixEnvironImpact instantiates a new CdrBodyTariffsEnergyMixEnvironImpact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrBodyTariffsEnergyMixEnvironImpact(category string, amount float32) *CdrBodyTariffsEnergyMixEnvironImpact {
	this := CdrBodyTariffsEnergyMixEnvironImpact{}
	this.Category = category
	this.Amount = amount
	return &this
}

// NewCdrBodyTariffsEnergyMixEnvironImpactWithDefaults instantiates a new CdrBodyTariffsEnergyMixEnvironImpact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrBodyTariffsEnergyMixEnvironImpactWithDefaults() *CdrBodyTariffsEnergyMixEnvironImpact {
	this := CdrBodyTariffsEnergyMixEnvironImpact{}
	return &this
}

// GetCategory returns the Category field value
func (o *CdrBodyTariffsEnergyMixEnvironImpact) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsEnergyMixEnvironImpact) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *CdrBodyTariffsEnergyMixEnvironImpact) SetCategory(v string) {
	o.Category = v
}

// GetAmount returns the Amount field value
func (o *CdrBodyTariffsEnergyMixEnvironImpact) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsEnergyMixEnvironImpact) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CdrBodyTariffsEnergyMixEnvironImpact) SetAmount(v float32) {
	o.Amount = v
}

func (o CdrBodyTariffsEnergyMixEnvironImpact) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrBodyTariffsEnergyMixEnvironImpact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["category"] = o.Category
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

type NullableCdrBodyTariffsEnergyMixEnvironImpact struct {
	value *CdrBodyTariffsEnergyMixEnvironImpact
	isSet bool
}

func (v NullableCdrBodyTariffsEnergyMixEnvironImpact) Get() *CdrBodyTariffsEnergyMixEnvironImpact {
	return v.value
}

func (v *NullableCdrBodyTariffsEnergyMixEnvironImpact) Set(val *CdrBodyTariffsEnergyMixEnvironImpact) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrBodyTariffsEnergyMixEnvironImpact) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrBodyTariffsEnergyMixEnvironImpact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrBodyTariffsEnergyMixEnvironImpact(val *CdrBodyTariffsEnergyMixEnvironImpact) *NullableCdrBodyTariffsEnergyMixEnvironImpact {
	return &NullableCdrBodyTariffsEnergyMixEnvironImpact{value: val, isSet: true}
}

func (v NullableCdrBodyTariffsEnergyMixEnvironImpact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrBodyTariffsEnergyMixEnvironImpact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


