/*
OCPI modules

Specification for OCPIs modules handlers

API version: 2.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package OCPI

import (
	"encoding/json"
)

// checks if the CdrBodyTariffsEnergyMixEnergySources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdrBodyTariffsEnergyMixEnergySources{}

// CdrBodyTariffsEnergyMixEnergySources struct for CdrBodyTariffsEnergyMixEnergySources
type CdrBodyTariffsEnergyMixEnergySources struct {
	Source string `json:"source"`
	Percentage float32 `json:"percentage"`
}

// NewCdrBodyTariffsEnergyMixEnergySources instantiates a new CdrBodyTariffsEnergyMixEnergySources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdrBodyTariffsEnergyMixEnergySources(source string, percentage float32) *CdrBodyTariffsEnergyMixEnergySources {
	this := CdrBodyTariffsEnergyMixEnergySources{}
	this.Source = source
	this.Percentage = percentage
	return &this
}

// NewCdrBodyTariffsEnergyMixEnergySourcesWithDefaults instantiates a new CdrBodyTariffsEnergyMixEnergySources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdrBodyTariffsEnergyMixEnergySourcesWithDefaults() *CdrBodyTariffsEnergyMixEnergySources {
	this := CdrBodyTariffsEnergyMixEnergySources{}
	return &this
}

// GetSource returns the Source field value
func (o *CdrBodyTariffsEnergyMixEnergySources) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsEnergyMixEnergySources) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *CdrBodyTariffsEnergyMixEnergySources) SetSource(v string) {
	o.Source = v
}

// GetPercentage returns the Percentage field value
func (o *CdrBodyTariffsEnergyMixEnergySources) GetPercentage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value
// and a boolean to check if the value has been set.
func (o *CdrBodyTariffsEnergyMixEnergySources) GetPercentageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percentage, true
}

// SetPercentage sets field value
func (o *CdrBodyTariffsEnergyMixEnergySources) SetPercentage(v float32) {
	o.Percentage = v
}

func (o CdrBodyTariffsEnergyMixEnergySources) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdrBodyTariffsEnergyMixEnergySources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["percentage"] = o.Percentage
	return toSerialize, nil
}

type NullableCdrBodyTariffsEnergyMixEnergySources struct {
	value *CdrBodyTariffsEnergyMixEnergySources
	isSet bool
}

func (v NullableCdrBodyTariffsEnergyMixEnergySources) Get() *CdrBodyTariffsEnergyMixEnergySources {
	return v.value
}

func (v *NullableCdrBodyTariffsEnergyMixEnergySources) Set(val *CdrBodyTariffsEnergyMixEnergySources) {
	v.value = val
	v.isSet = true
}

func (v NullableCdrBodyTariffsEnergyMixEnergySources) IsSet() bool {
	return v.isSet
}

func (v *NullableCdrBodyTariffsEnergyMixEnergySources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdrBodyTariffsEnergyMixEnergySources(val *CdrBodyTariffsEnergyMixEnergySources) *NullableCdrBodyTariffsEnergyMixEnergySources {
	return &NullableCdrBodyTariffsEnergyMixEnergySources{value: val, isSet: true}
}

func (v NullableCdrBodyTariffsEnergyMixEnergySources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdrBodyTariffsEnergyMixEnergySources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


